"""
Generate realistic mock incident tickets for PoC validation.

Run:  python seed_data.py
"""

from db import ingest_tickets_batch
from models import Base, engine

SEED_TICKETS = [
    # ═══ Category: Database ═══
    {
        "incident_no": "INC-2024-0001",
        "title": "MySQL master CPU 100% after traffic spike",
        "description": "mysql-master-01 CPU hit 100% at 14:32 UTC. Replication lag grew to 45s on slave-01. Application error rate spiked to 12%. Slow query log shows 10x increase in SELECT * FROM orders WHERE status='pending'.",
        "root_cause": "Missing composite index on (user_id, status) caused full-table scan of 8M-row orders table during a promotion campaign. Connection pool exhausted as each query took 8s instead of 50ms.",
        "resolution": "1. Added composite index CREATE INDEX idx_orders_user_status ON orders(user_id, status). 2. Set max_execution_time=2000 on the session pool. 3. Scaled read-replicas from 2 to 4 temporarily. Index brought query time down to 40ms.",
        "action_plan": "1. Immediate: kill long-running queries, enable query cache. 2. Analyze slow-query-log to identify missing indexes. 3. Add index, verify EXPLAIN plan. 4. Scale replicas if needed. 5. Set up slow-query alerting.",
        "severity": "P0",
        "service_name": "order-service",
        "category": "database",
        "status": "resolved",
        "error_type": "timeout",
    },
    {
        "incident_no": "INC-2024-0002",
        "incident_no": "INC-2024-0002",
        "title": "PostgreSQL connection pool exhausted during black-friday",
        "description": "PG connection pool maxed out at 500 connections. New requests failing with 'FATAL: sorry, too many clients already'. Latency p99 went from 80ms to 12s. HikariCP metrics show active connections stuck at max for 20min.",
        "root_cause": "A new deployment introduced N+1 queries in the product-listing endpoint. Each page view spawned 200+ individual queries instead of 1 JOIN. Connection pool drained in 3min under peak traffic.",
        "resolution": "1. Rolled back deployment to previous version. 2. Rewrote product-listing query to use a single JOIN with eager loading. 3. Increased pool size from 50 to 150 per instance. 4. Added pgbouncer transaction pooling.",
        "action_plan": "1. Immediate: rollback deployment if recent, else kill idle connections. 2. Check pg_stat_activity for query patterns. 3. Identify N+1 patterns in application code. 4. Add pgbouncer. 5. Set connection timeout to 10s.",
        "severity": "P0",
        "service_name": "product-service",
        "category": "database",
        "status": "resolved",
        "error_type": "timeout",
    },
    {
        "incident_no": "INC-2024-0003",
        "title": "Redis cluster OOM evicting keys under load",
        "description": "Redis cluster nodes started evicting keys due to maxmemory limit. Cache hit rate dropped from 98% to 23% within 5min. Backend MySQL read QPS jumped 15x causing cascading latency.",
        "root_cause": "Background job updated 2M user session entries with TTL=0 (no expiry), saturating Redis memory. Eviction policy was allkeys-lru, so hot cache keys were evicted, exposing bare DB.",
        "resolution": "1. Manually set TTL on oversized keys via SCAN+EXPIRE. 2. Changed eviction policy to volatile-lru. 3. Added memory monitoring with 80% threshold alert. 4. Set maxmemory-policy noeviction for session keys.",
        "action_plan": "1. Immediate: identify and expire bloated keys. 2. Check INFO memory and MONITOR for write patterns. 3. Switch eviction policy if needed. 4. Add memory alerts at 70%/85%. 5. Audit all code paths that SET without TTL.",
        "severity": "P1",
        "service_name": "session-service",
        "category": "database",
        "status": "resolved",
        "error_type": "OOM",
    },
    {
        "incident_no": "INC-2024-0004",
        "title": "Deadlock on inventory deduction during flash sale",
        "description": "Multiple concurrent transactions deadlocking on inventory UPDATE. Error log shows 'Deadlock found when trying to get lock; try restarting transaction'. 40% of checkout attempts failed.",
        "root_cause": "Inventory deduction logic used SELECT ... FOR UPDATE on item_id then UPDATE on warehouse_id in different order across two code paths (order vs. refund). Inconsistent lock ordering caused deadlock.",
        "resolution": "1. Standardized lock ordering: always lock warehouse first, then item. 2. Wrapped both UPDATEs in a single CTE to reduce lock duration. 3. Added retry with exponential backoff in application layer.",
        "action_plan": "1. Immediate: restart stuck transactions via pg_terminate_backend. 2. Capture deadlock logs from pg_stat_activity. 3. Audit lock ordering in all inventory code paths. 4. Add retry logic. 5. Consider optimistic locking via version column.",
        "severity": "P0",
        "service_name": "inventory-service",
        "category": "database",
        "status": "resolved",
        "error_type": "deadlock",
    },
    {
        "incident_no": "INC-2024-0005",
        "title": "Elasticsearch cluster red status — unassigned shards",
        "description": "ES cluster went red after node-03 was terminated by OOM killer. 12 primary shards unassigned. Search API returning 503 for 30% of queries. Indexing rate dropped to zero.",
        "root_cause": "Node-03 held 12 primary shards with replica=0. Node crash left shards unassigned with no replica to promote. OOM was caused by a bulk reindex job that allocated 8GB heap, exceeding the 4GB Xmx limit.",
        "resolution": "1. Used _cluster/reroute to allocate stale primary shards (accept_data_loss=true, since replicas already 0). 2. Increased heap to 8GB with proper Xmx/Xms alignment. 3. Set replica=1 for all critical indices.",
        "action_plan": "1. Immediate: reroute unassigned shards. 2. Check _cluster/health and _cat/shards. 3. Ensure all indices have >=1 replica. 4. Review JVM heap config. 5. Add disk watermark alerts.",
        "severity": "P0",
        "service_name": "search-service",
        "category": "database",
        "status": "resolved",
        "error_type": "OOM",
    },
    # ═══ Category: Network ═══
    {
        "incident_no": "INC-2024-0006",
        "title": "Intermittent 502 errors between API gateway and upstream",
        "description": "API gateway logging intermittent 502 Bad Gateway errors (5% of requests). Upstream health checks passing. No error in upstream application logs. tcpdump shows RST packets during affected windows. Duration: 3min bursts every 15min.",
        "root_cause": "AWS NLB idle timeout was set to 350s. Application keepalive was 360s. During low traffic, connections idled past NLB timeout and were silently dropped. Next request on the stale connection got RST, returning 502.",
        "resolution": "1. Set application keepalive to 300s (below NLB's 350s). 2. Enabled connection pooling with TTL=240s. 3. Added retry with backoff on 502 in gateway config. 502 rate dropped to 0%.",
        "action_plan": "1. Check load-balancer idle timeout vs application keepalive. 2. Capture packet trace for RST analysis. 3. Adjust keepalive to be LOWER than LB timeout. 4. Add health-check interval tuning.",
        "severity": "P1",
        "service_name": "api-gateway",
        "category": "network",
        "status": "resolved",
        "error_type": "timeout",
    },
    {
        "incident_no": "INC-2024-0007",
        "title": "DNS resolution failures causing cascading service outages",
        "description": "Multiple services reporting UnknownHostException. /etc/resolv.conf shows correct nameservers. dig commands timeout intermittently. Affected: payment-service, notification-service, user-service. Impact: 25% of transactions failing.",
        "root_cause": "CoreDNS pods in k8s cluster were hitting their 9984-concurrent-request limit. A new deployment of 50 pods simultaneously sent DNS queries at startup, creating a thundering-herd effect. CoreDNS autoscaler was misconfigured with min=1.",
        "resolution": "1. Scaled CoreDNS to 5 replicas. 2. Set podAntiAffinity to spread across nodes. 3. Added ndots:2 to resolv.conf to reduce query volume. 4. Adjusted CoreDNS autoscaler to min=3 with CPU threshold 60%.",
        "action_plan": "1. Immediate: scale DNS replicas. 2. Check DNS query rate and latency. 3. Verify CoreDNS autoscaler config. 4. Review ndots setting in resolv.conf. 5. Consider node-local DNS cache.",
        "severity": "P0",
        "service_name": "infra-dns",
        "category": "network",
        "status": "resolved",
        "error_type": "timeout",
    },
    {
        "incident_no": "INC-2024-0008",
        "title": "TLS certificate expiry causing HTTPS connection failures",
        "description": "prod.example.com TLS certificate expired at 00:00 UTC. All HTTPS connections rejected with SSL_ERROR_EXPIRED_CERTIFICATE. Users unable to login. Mobile app returning network error on all endpoints.",
        "root_cause": "Let's Encrypt auto-renewal cron job on certbot was silently failing for 30 days due to incorrect IAM role permission change on Route53 DNS validation. Manual renewal had not been performed.",
        "resolution": "1. Manually renewed cert via certbot --force-renewal. 2. Restarted nginx to pick up new cert. 3. Fixed IAM role to allow route53:ChangeResourceRecordSets. 4. Added Prometheus alert for cert_expiry_days < 14.",
        "action_plan": "1. Immediate: manual cert renewal + reload. 2. Verify expiry dates via openssl s_client. 3. Check auto-renewal logs. 4. Fix IAM perms if using DNS challenge. 5. Add cert monitoring + alerting.",
        "severity": "P0",
        "service_name": "api-gateway",
        "category": "network",
        "status": "resolved",
        "error_type": "auth_error",
    },
    {
        "incident_no": "INC-2024-0009",
        "title": "Kubernetes service mesh sidecar memory leak",
        "description": "Envoy sidecars across 3 services showing steady RSS growth from 200MB to 2GB over 6h. Nodes running out of allocatable memory. OOMKiller terminating sidecars causing traffic disruption.",
        "root_cause": "Envoy 1.26.0 had a known memory leak in the ext_authz filter when upstream auth service returns 5xx. Each failed auth request leaked ~2KB. With 100 auth failures/s over 6h = ~4GB leaked total.",
        "resolution": "1. Upgraded Envoy sidecar from 1.26.0 to 1.26.4 (leak fixed). 2. Added sidecar memory limit of 512Mi with OOM score adjustment. 3. Set ext_authz failure_mode_allow to false to fail closed. 4. Put circuit breaker on auth service to return 429 at 80% capacity.",
        "action_plan": "1. Immediate: restart leaking sidecars. 2. Identify Envoy version, check release notes. 3. Upgrade if known leak. 4. Add memory limits per sidecar. 5. Set up sidecar memory monitoring.",
        "severity": "P1",
        "service_name": "istio-mesh",
        "category": "network",
        "status": "resolved",
        "error_type": "OOM",
    },
    {
        "incident_no": "INC-2024-0010",
        "title": "Cross-AZ network latency spike during AZ failover",
        "description": "Inter-AZ latency jumped from 2ms to 200ms between AZ-a and AZ-b. Synchronous replication delayed by 15s. Consensus (Raft) leader election flapping. Cluster in split-brain risk.",
        "root_cause": "AWS Direct Connect fiber cut in us-east-1 reduced inter-AZ bandwidth, causing congestion and bufferbloat. Traffic was routed through a saturated backup path. AWS Status Dashboard confirmed the incident 15min after detection.",
        "resolution": "1. Triggered manual AZ isolation to route all traffic within AZ-a only. 2. Promoted local replicas to primary to avoid cross-AZ consensus. 3. AWS resolved the fiber issue after 2h. 4. Added cross-AZ latency alert >10ms.",
        "action_plan": "1. Immediate: check cloud provider status. 2. Isolate to single AZ if possible. 3. Promote local replicas. 4. Add cross-AZ latency monitoring. 5. Review multi-AZ architecture for single-AZ degradation modes.",
        "severity": "P0",
        "service_name": "etcd-cluster",
        "category": "network",
        "status": "resolved",
        "error_type": "timeout",
    },
    # ═══ Category: Application ═══
    {
        "incident_no": "INC-2024-0011",
        "title": "Java OOM heap dump after rolling deployment",
        "description": "After deploying v2.4.1 to production, 3 out of 10 instances crashed with java.lang.OutOfMemoryError: Java heap space within 10min. Heap dump shows 4.2GB occupied by byte[] (90%). GC logs show full GC every 8s with no reclaim.",
        "root_cause": "v2.4.1 introduced a CSV export feature that loaded the entire result set into memory using ByteArrayOutputStream. A user triggered export of 5M rows (2GB CSV in memory * 2 threads = 4GB). No streaming or row-limit was implemented.",
        "resolution": "1. Rolled back to v2.4.0. 2. Rewrote CSV export to use StreamingResponseBody with chunked writes (no full in-memory load). 3. Added row limit of 100K for exports with cursor pagination. 4. Set -XX:+HeapDumpOnOutOfMemoryError -Xmx2g.",
        "action_plan": "1. Immediate: rollback deployment. 2. Capture heap dump for analysis. 3. Identify memory hotspot (often byte[] for serialization). 4. Switch to streaming/chunked I/O. 5. Add row limits. 6. Review JVM GC settings.",
        "severity": "P0",
        "service_name": "reporting-service",
        "category": "application",
        "status": "resolved",
        "error_type": "OOM",
    },
    {
        "incident_no": "INC-2024-0012",
        "title": "Node.js event loop blocked causing health check timeouts",
        "description": "Node.js app health-check endpoint timing out (3s threshold). Event loop lag metric shows 4200ms max. CPU at 30% — not CPU-bound. Heap 150MB/512MB — not GC thrashing. Requests queued but not processed.",
        "root_cause": "Synchronous crypto.randomBytes(256) called inside a hot-path request handler. It blocked the event loop while waiting for entropy. Under 500 concurrent connections, each blocking call queued up, cascading to full event-loop starvation.",
        "resolution": "1. Replaced crypto.randomBytes with crypto.randomBytes (async/callback version). 2. Added --trace-event-loop to identify other blocking calls. 3. Set up event-loop-lag alert at >200ms. 4. Moved heavy crypto to worker_threads pool.",
        "action_plan": "1. Identify blocking calls via --trace-event-loop or clinic.js. 2. Replace sync crypto, fs, zlib calls with async equivalents. 3. Offload CPU-heavy work to worker threads. 4. Add event-loop lag monitoring.",
        "severity": "P1",
        "service_name": "auth-service",
        "category": "application",
        "status": "resolved",
        "error_type": "timeout",
    },
    {
        "incident_no": "INC-2024-0013",
        "title": "Race condition in order status state machine",
        "description": "Orders stuck in 'processing' state after payment confirmation webhook. Payment provider confirmed success but order never transitioned to 'confirmed'. DB shows payment.status='paid' but order.status='processing'. Affects 3% of orders.",
        "root_cause": "Race condition: payment webhook and order timeout-cancel job both read order.status='processing', then each tried to UPDATE to 'confirmed' and 'cancelled' respectively. The job that arrived second won, overwriting the first transition with a lost update.",
        "resolution": "1. Added SELECT ... FOR UPDATE in order status transition to serialize access. 2. Changed to UPDATE orders SET status='confirmed' WHERE status='processing' (compare-and-swap). 3. Added idempotency key on webhook handler. 4. Built reconciliation job to fix stuck orders.",
        "action_plan": "1. Immediate: identify and manually fix stuck orders. 2. Add pessimistic locking on status transitions. 3. Use CAS UPDATE pattern (WHERE current_status = expected). 4. Add idempotency for webhooks. 5. Create reconciliation background job.",
        "severity": "P1",
        "service_name": "order-service",
        "category": "application",
        "status": "resolved",
        "error_type": "race_condition",
    },
    {
        "incident_no": "INC-2024-0014",
        "title": "Memory leak in Python service after 48h uptime",
        "description": "Python (FastAPI) service memory RSS grows from 200MB to 3.5GB over 48h, then gets OOMKilled. Memory profiling with tracemalloc shows top allocation: asyncio.Task objects (2.1M instances). No GC collection of completed tasks.",
        "root_cause": "asyncio.create_task() was called in a request handler without storing the task reference or awaiting it. Python's GC doesn't collect running tasks. Under load, 200 completed-but-unreferenced tasks leaked per second, accumulating 2M tasks over 48h.",
        "resolution": "1. Added TaskSet utility to track spawned tasks and clean up on completion. 2. Set asyncio.Task.add_done_callback to self-remove. 3. Added max-concurrent-tasks semaphore (limit 100). 4. Deploy with --max-requests 10000 + pre-emptive restart at 24h as safety net.",
        "action_plan": "1. Profile memory with tracemalloc. 2. Identify leaked object types (Task, connection, dict). 3. Ensure tasks are cleaned up on completion. 4. Add concurrency limits. 5. Consider pre-emptive restart as safety net.",
        "severity": "P2",
        "service_name": "notification-service",
        "category": "application",
        "status": "resolved",
        "error_type": "OOM",
    },
    {
        "incident_no": "INC-2024-0015",
        "title": "gRPC deadline exceeded on recommendation service",
        "description": "recommendation-service gRPC calls failing with DEADLINE_EXCEEDED. P99 latency 8s (SLO: 300ms). Upstream ML model serving responds in 150ms — delay is NOT in the model. Tracing shows time spent in gRPC layer waiting for connection.",
        "root_cause": "gRPC channel pool was configured with maxConnections=5 but the load balancer was distributing 500 req/s across 5 connections. TCP head-of-line blocking caused later requests on the same connection to wait for earlier slow responses. The slow responses were themselves caused by HOL blocking (vicious cycle).",
        "resolution": "1. Increased maxConnections from 5 to 200 (one per concurrent request). 2. Enabled HTTP/2 max concurrent streams = 1 to prevent HOL at gRPC level. 3. Set keepalive with timeout=10s and permit-keepalive-without-calls. 4. Changed to round_robin LB policy.",
        "action_plan": "1. Check gRPC channel pool size and LB policy. 2. Increase connections per instance. 3. Set max concurrent streams = 1. 4. Tune keepalive settings. 5. Check for HOL blocking via tracing spans.",
        "severity": "P1",
        "service_name": "recommendation-service",
        "category": "application",
        "status": "resolved",
        "error_type": "timeout",
    },
    # ═══ Category: Infrastructure ═══
    {
        "incident_no": "INC-2024-0016",
        "title": "Kubernetes node NotReady — disk pressure",
        "description": "Node ip-10-0-3-45 went NotReady. kubelet logs show 'DiskPressure: available 3%'. Pods on this node being evicted. Node has 100GB EBS, df shows /var/lib/docker 92% full. New pod scheduling failing across the cluster.",
        "root_cause": "Docker image garbage collection threshold was set to 90% but node-slow disk alert was set to 85% (below GC trigger). Old images accumulated during 4 deployments/day without cleanup. Over 2 weeks, unused images consumed 60GB.",
        "resolution": "1. Manually ran docker image prune -a -f to free 55GB. 2. Lowered image GC threshold to 70%. 3. Added kubelet flag --image-gc-high-threshold=70. 4. Added disk usage alert at 75% (above GC but before pressure).",
        "action_plan": "1. Immediate: prune unused Docker images. 2. Check kubelet image GC thresholds. 3. Set GC threshold below alert threshold. 4. Add disk pressure monitoring per node.",
        "severity": "P1",
        "service_name": "k8s-cluster",
        "category": "infrastructure",
        "status": "resolved",
        "error_type": "resource_exhaustion",
    },
    {
        "incident_no": "INC-2024-0017",
        "title": "AWS ECS service unable to place tasks — insufficient memory",
        "description": "ECS service deploy rolling update stuck for 30min. Events log: 'service xxx was unable to place a task because no container instance met all of its requirements'. Cluster all instances at 95%+ memory reservation.",
        "root_cause": "New deployment bumped task memory from 512MB to 1024MB (soft limit). ECS scheduler needs to place new task before draining old one (rolling update). With existing 512MB*8 tasks = 4GB reserved, no instance had 1GB free for the new task.",
        "resolution": "1. Temporarily scaled out cluster by 2 instances via ASG desired count. 2. Let deployment complete. 3. Scaled back in after old tasks drained. 4. Updated capacity planning to account for burst headroom during deployments (1.5x peak).",
        "action_plan": "1. Immediate: add cluster capacity (new instances). 2. Check ECS events for placement failures. 3. Calculate headroom needed for rolling update. 4. Adjust cluster autoscaling to maintain burst buffer. 5. Review per-task memory reservations.",
        "severity": "P1",
        "service_name": "ecs-cluster",
        "category": "infrastructure",
        "status": "resolved",
        "error_type": "resource_exhaustion",
    },
    {
        "incident_no": "INC-2024-0018",
        "title": "Prometheus disk full — time-series database corruption",
        "description": "Prometheus pod crash looping with 'opening storage failed: /prometheus/01H...: invalid magic number 0'. Disk 100% full. TSDB WAL checkpoint corrupted. Monitoring blackout — no metrics for last 20min across entire org.",
        "root_cause": "Cardinality explosion: a new deployment added a label 'request_id' (UUID) to all HTTP metrics. Each unique UUID created a new time series. From 50K to 15M active series in 2h. TSDB WAL grew from 2GB to 50GB, filling the 80GB PVC.",
        "resolution": "1. Restored from last TSDB snapshot (30min data loss). 2. Rolled back deployment that added request_id label. 3. Added relabel_config to drop request_id at scrape time. 4. Set --storage.tsdb.retention.size=60GB. 5. Added cardinality alert at 500K series.",
        "action_plan": "1. Immediate: check disk space, restore from snapshot if corrupted. 2. Identify cardinality spike source (label values). 3. Drop high-cardinality labels. 4. Set retention size limit. 5. Add cardinality + disk alerts.",
        "severity": "P0",
        "service_name": "monitoring",
        "category": "infrastructure",
        "status": "resolved",
        "error_type": "resource_exhaustion",
    },
    {
        "incident_no": "INC-2024-0019",
        "title": "CI/CD pipeline hung on git clone — GitHub rate limit",
        "description": "All CI/CD pipelines stuck at 'git clone' step. Error: 'remote: Repository not found. fatal: Authentication failed...' — but credentials are correct. Started at 14:00 UTC across all pipelines simultaneously.",
        "root_cause": "Organization hit GitHub's secondary rate limit (100 concurrent git operations per org). A scheduled job triggered 200 parallel builds, each doing git clone simultaneously. GitHub returned 429s which the runner interpreted as auth failure.",
        "resolution": "1. Cancelled 150 queued builds to drop below rate limit. 2. Configured git clone --depth=1 to reduce data transfer. 3. Added git cache proxy (git-cache) to serve clones from within VPC. 4. Implemented staggered scheduling (max 50 concurrent clones).",
        "action_plan": "1. Immediate: cancel excessive builds. 2. Check GitHub rate-limit headers. 3. Set up git cache/mirror internally. 4. Implement clone staggering. 5. Use shallow clones where possible.",
        "severity": "P1",
        "service_name": "cicd-pipeline",
        "category": "infrastructure",
        "status": "resolved",
        "error_type": "rate_limit",
    },
    {
        "incident_no": "INC-2024-0020",
        "title": "Terraform state lock timeout blocking all deployments",
        "description": "All terraform apply commands failing with 'Error acquiring the state lock: ConditionalCheckFailedException'. Lock held for 45min. DynamoDB lock table shows lock acquired by a CI run that was terminated by timeout. No heartbeat to release.",
        "root_cause": "CI job (terraform plan) acquired state lock, then exceeded its 30min timeout. The runner was killed but never ran terraform force-unlock. DynamoDB item persisted without TTL. Manual intervention required to delete lock.",
        "resolution": "1. Manually deleted lock item from DynamoDB via AWS Console. 2. Added TTL attribute to lock items (auto-expire after 15min). 3. Reduced terraform plan timeout to 20min. 4. Added pre-kill signal handler (SIGTERM → terraform force-unlock).",
        "action_plan": "1. Immediate: force-unlock or delete lock from DynamoDB. 2. Check who acquired lock and why it stalled. 3. Add TTL to lock table items. 4. Implement graceful unlock on SIGTERM. 5. Set CI timeouts below lock TTL.",
        "severity": "P1",
        "service_name": "infra-tf",
        "category": "infrastructure",
        "status": "resolved",
        "error_type": "deadlock",
    },
]


def seed():
    Base.metadata.create_all(engine)
    print("Tables created (if not existed).")

    ids = ingest_tickets_batch(SEED_TICKETS)
    print(f"Seeded {len(ids)} tickets:")
    for i, tid in enumerate(ids):
        print(f"  [{i+1}] {tid}")
    print("Done.")


if __name__ == "__main__":
    seed()
