"""
Generate realistic mock incident tickets for PoC validation.

Run:  python seed_data.py
"""

from db import ingest_tickets_batch
from models import Base, engine

SEED_TICKETS = [
    # ═══ Category: Database ═══
    {
        "incident_no": "INC-2024-0001",
        "title": "MySQL master CPU 100% after traffic spike",
        "description": "mysql-master-01 CPU hit 100% at 14:32 UTC. Replication lag grew to 45s on slave-01. Application error rate spiked to 12%. Slow query log shows 10x increase in SELECT * FROM orders WHERE status='pending'.",
        "root_cause": "Missing composite index on (user_id, status) caused full-table scan of 8M-row orders table during a promotion campaign. Connection pool exhausted as each query took 8s instead of 50ms.",
        "resolution": "1. Added composite index CREATE INDEX idx_orders_user_status ON orders(user_id, status). 2. Set max_execution_time=2000 on the session pool. 3. Scaled read-replicas from 2 to 4 temporarily. Index brought query time down to 40ms.",
        "action_plan": "1. Immediate: kill long-running queries, enable query cache. 2. Analyze slow-query-log to identify missing indexes. 3. Add index, verify EXPLAIN plan. 4. Scale replicas if needed. 5. Set up slow-query alerting.",
        "severity": "P0",
        "service_name": "order-service",
        "category": "database",
        "status": "resolved",
        "error_type": "timeout",
    },
    {
        "incident_no": "INC-2024-0002",
        "title": "PostgreSQL connection pool exhausted during black-friday",
        "description": "PG connection pool maxed out at 500 connections. New requests failing with 'FATAL: sorry, too many clients already'. Latency p99 went from 80ms to 12s. HikariCP metrics show active connections stuck at max for 20min.",
        "root_cause": "A new deployment introduced N+1 queries in the product-listing endpoint. Each page view spawned 200+ individual queries instead of 1 JOIN. Connection pool drained in 3min under peak traffic.",
        "resolution": "1. Rolled back deployment to previous version. 2. Rewrote product-listing query to use a single JOIN with eager loading. 3. Increased pool size from 50 to 150 per instance. 4. Added pgbouncer transaction pooling.",
        "action_plan": "1. Immediate: rollback deployment if recent, else kill idle connections. 2. Check pg_stat_activity for query patterns. 3. Identify N+1 patterns in application code. 4. Add pgbouncer. 5. Set connection timeout to 10s.",
        "severity": "P0",
        "service_name": "product-service",
        "category": "database",
        "status": "resolved",
        "error_type": "timeout",
    },
    {
        "incident_no": "INC-2024-0003",
        "title": "Redis cluster OOM evicting keys under load",
        "description": "Redis cluster nodes started evicting keys due to maxmemory limit. Cache hit rate dropped from 98% to 23% within 5min. Backend MySQL read QPS jumped 15x causing cascading latency.",
        "root_cause": "Background job updated 2M user session entries with TTL=0 (no expiry), saturating Redis memory. Eviction policy was allkeys-lru, so hot cache keys were evicted, exposing bare DB.",
        "resolution": "1. Manually set TTL on oversized keys via SCAN+EXPIRE. 2. Changed eviction policy to volatile-lru. 3. Added memory monitoring with 80% threshold alert. 4. Set maxmemory-policy noeviction for session keys.",
        "action_plan": "1. Immediate: identify and expire bloated keys. 2. Check INFO memory and MONITOR for write patterns. 3. Switch eviction policy if needed. 4. Add memory alerts at 70%/85%. 5. Audit all code paths that SET without TTL.",
        "severity": "P1",
        "service_name": "session-service",
        "category": "database",
        "status": "resolved",
        "error_type": "OOM",
    },
    {
        "incident_no": "INC-2024-0004",
        "title": "Deadlock on inventory deduction during flash sale",
        "description": "Multiple concurrent transactions deadlocking on inventory UPDATE. Error log shows 'Deadlock found when trying to get lock; try restarting transaction'. 40% of checkout attempts failed.",
        "root_cause": "Inventory deduction logic used SELECT ... FOR UPDATE on item_id then UPDATE on warehouse_id in different order across two code paths (order vs. refund). Inconsistent lock ordering caused deadlock.",
        "resolution": "1. Standardized lock ordering: always lock warehouse first, then item. 2. Wrapped both UPDATEs in a single CTE to reduce lock duration. 3. Added retry with exponential backoff in application layer.",
        "action_plan": "1. Immediate: restart stuck transactions via pg_terminate_backend. 2. Capture deadlock logs from pg_stat_activity. 3. Audit lock ordering in all inventory code paths. 4. Add retry logic. 5. Consider optimistic locking via version column.",
        "severity": "P0",
        "service_name": "inventory-service",
        "category": "database",
        "status": "resolved",
        "error_type": "deadlock",
    },
    {
        "incident_no": "INC-2024-0005",
        "title": "Elasticsearch cluster red status — unassigned shards",
        "description": "ES cluster went red after node-03 was terminated by OOM killer. 12 primary shards unassigned. Search API returning 503 for 30% of queries. Indexing rate dropped to zero.",
        "root_cause": "Node-03 held 12 primary shards with replica=0. Node crash left shards unassigned with no replica to promote. OOM was caused by a bulk reindex job that allocated 8GB heap, exceeding the 4GB Xmx limit.",
        "resolution": "1. Used _cluster/reroute to allocate stale primary shards (accept_data_loss=true, since replicas already 0). 2. Increased heap to 8GB with proper Xmx/Xms alignment. 3. Set replica=1 for all critical indices.",
        "action_plan": "1. Immediate: reroute unassigned shards. 2. Check _cluster/health and _cat/shards. 3. Ensure all indices have >=1 replica. 4. Review JVM heap config. 5. Add disk watermark alerts.",
        "severity": "P0",
        "service_name": "search-service",
        "category": "database",
        "status": "resolved",
        "error_type": "OOM",
    },
    # ═══ Category: Network ═══
    {
        "incident_no": "INC-2024-0006",
        "title": "Intermittent 502 errors between API gateway and upstream",
        "description": "API gateway logging intermittent 502 Bad Gateway errors (5% of requests). Upstream health checks passing. No error in upstream application logs. tcpdump shows RST packets during affected windows. Duration: 3min bursts every 15min.",
        "root_cause": "AWS NLB idle timeout was set to 350s. Application keepalive was 360s. During low traffic, connections idled past NLB timeout and were silently dropped. Next request on the stale connection got RST, returning 502.",
        "resolution": "1. Set application keepalive to 300s (below NLB's 350s). 2. Enabled connection pooling with TTL=240s. 3. Added retry with backoff on 502 in gateway config. 502 rate dropped to 0%.",
        "action_plan": "1. Check load-balancer idle timeout vs application keepalive. 2. Capture packet trace for RST analysis. 3. Adjust keepalive to be LOWER than LB timeout. 4. Add health-check interval tuning.",
        "severity": "P1",
        "service_name": "api-gateway",
        "category": "network",
        "status": "resolved",
        "error_type": "timeout",
    },
    {
        "incident_no": "INC-2024-0007",
        "title": "DNS resolution failures causing cascading service outages",
        "description": "Multiple services reporting UnknownHostException. /etc/resolv.conf shows correct nameservers. dig commands timeout intermittently. Affected: payment-service, notification-service, user-service. Impact: 25% of transactions failing.",
        "root_cause": "CoreDNS pods in k8s cluster were hitting their 9984-concurrent-request limit. A new deployment of 50 pods simultaneously sent DNS queries at startup, creating a thundering-herd effect. CoreDNS autoscaler was misconfigured with min=1.",
        "resolution": "1. Scaled CoreDNS to 5 replicas. 2. Set podAntiAffinity to spread across nodes. 3. Added ndots:2 to resolv.conf to reduce query volume. 4. Adjusted CoreDNS autoscaler to min=3 with CPU threshold 60%.",
        "action_plan": "1. Immediate: scale DNS replicas. 2. Check DNS query rate and latency. 3. Verify CoreDNS autoscaler config. 4. Review ndots setting in resolv.conf. 5. Consider node-local DNS cache.",
        "severity": "P0",
        "service_name": "infra-dns",
        "category": "network",
        "status": "resolved",
        "error_type": "timeout",
    },
    {
        "incident_no": "INC-2024-0008",
        "title": "TLS certificate expiry causing HTTPS connection failures",
        "description": "prod.example.com TLS certificate expired at 00:00 UTC. All HTTPS connections rejected with SSL_ERROR_EXPIRED_CERTIFICATE. Users unable to login. Mobile app returning network error on all endpoints.",
        "root_cause": "Let's Encrypt auto-renewal cron job on certbot was silently failing for 30 days due to incorrect IAM role permission change on Route53 DNS validation. Manual renewal had not been performed.",
        "resolution": "1. Manually renewed cert via certbot --force-renewal. 2. Restarted nginx to pick up new cert. 3. Fixed IAM role to allow route53:ChangeResourceRecordSets. 4. Added Prometheus alert for cert_expiry_days < 14.",
        "action_plan": "1. Immediate: manual cert renewal + reload. 2. Verify expiry dates via openssl s_client. 3. Check auto-renewal logs. 4. Fix IAM perms if using DNS challenge. 5. Add cert monitoring + alerting.",
        "severity": "P0",
        "service_name": "api-gateway",
        "category": "network",
        "status": "resolved",
        "error_type": "auth_error",
    },
    {
        "incident_no": "INC-2024-0009",
        "title": "Kubernetes service mesh sidecar memory leak",
        "description": "Envoy sidecars across 3 services showing steady RSS growth from 200MB to 2GB over 6h. Nodes running out of allocatable memory. OOMKiller terminating sidecars causing traffic disruption.",
        "root_cause": "Envoy 1.26.0 had a known memory leak in the ext_authz filter when upstream auth service returns 5xx. Each failed auth request leaked ~2KB. With 100 auth failures/s over 6h = ~4GB leaked total.",
        "resolution": "1. Upgraded Envoy sidecar from 1.26.0 to 1.26.4 (leak fixed). 2. Added sidecar memory limit of 512Mi with OOM score adjustment. 3. Set ext_authz failure_mode_allow to false to fail closed. 4. Put circuit breaker on auth service to return 429 at 80% capacity.",
        "action_plan": "1. Immediate: restart leaking sidecars. 2. Identify Envoy version, check release notes. 3. Upgrade if known leak. 4. Add memory limits per sidecar. 5. Set up sidecar memory monitoring.",
        "severity": "P1",
        "service_name": "istio-mesh",
        "category": "network",
        "status": "resolved",
        "error_type": "OOM",
    },
    {
        "incident_no": "INC-2024-0010",
        "title": "Cross-AZ network latency spike during AZ failover",
        "description": "Inter-AZ latency jumped from 2ms to 200ms between AZ-a and AZ-b. Synchronous replication delayed by 15s. Consensus (Raft) leader election flapping. Cluster in split-brain risk.",
        "root_cause": "AWS Direct Connect fiber cut in us-east-1 reduced inter-AZ bandwidth, causing congestion and bufferbloat. Traffic was routed through a saturated backup path. AWS Status Dashboard confirmed the incident 15min after detection.",
        "resolution": "1. Triggered manual AZ isolation to route all traffic within AZ-a only. 2. Promoted local replicas to primary to avoid cross-AZ consensus. 3. AWS resolved the fiber issue after 2h. 4. Added cross-AZ latency alert >10ms.",
        "action_plan": "1. Immediate: check cloud provider status. 2. Isolate to single AZ if possible. 3. Promote local replicas. 4. Add cross-AZ latency monitoring. 5. Review multi-AZ architecture for single-AZ degradation modes.",
        "severity": "P0",
        "service_name": "etcd-cluster",
        "category": "network",
        "status": "resolved",
        "error_type": "timeout",
    },
    # ═══ Category: Application ═══
    {
        "incident_no": "INC-2024-0011",
        "title": "Java OOM heap dump after rolling deployment",
        "description": "After deploying v2.4.1 to production, 3 out of 10 instances crashed with java.lang.OutOfMemoryError: Java heap space within 10min. Heap dump shows 4.2GB occupied by byte[] (90%). GC logs show full GC every 8s with no reclaim.",
        "root_cause": "v2.4.1 introduced a CSV export feature that loaded the entire result set into memory using ByteArrayOutputStream. A user triggered export of 5M rows (2GB CSV in memory * 2 threads = 4GB). No streaming or row-limit was implemented.",
        "resolution": "1. Rolled back to v2.4.0. 2. Rewrote CSV export to use StreamingResponseBody with chunked writes (no full in-memory load). 3. Added row limit of 100K for exports with cursor pagination. 4. Set -XX:+HeapDumpOnOutOfMemoryError -Xmx2g.",
        "action_plan": "1. Immediate: rollback deployment. 2. Capture heap dump for analysis. 3. Identify memory hotspot (often byte[] for serialization). 4. Switch to streaming/chunked I/O. 5. Add row limits. 6. Review JVM GC settings.",
        "severity": "P0",
        "service_name": "reporting-service",
        "category": "application",
        "status": "resolved",
        "error_type": "OOM",
    },
    {
        "incident_no": "INC-2024-0012",
        "title": "Node.js event loop blocked causing health check timeouts",
        "description": "Node.js app health-check endpoint timing out (3s threshold). Event loop lag metric shows 4200ms max. CPU at 30% — not CPU-bound. Heap 150MB/512MB — not GC thrashing. Requests queued but not processed.",
        "root_cause": "Synchronous crypto.randomBytes(256) called inside a hot-path request handler. It blocked the event loop while waiting for entropy. Under 500 concurrent connections, each blocking call queued up, cascading to full event-loop starvation.",
        "resolution": "1. Replaced crypto.randomBytes with crypto.randomBytes (async/callback version). 2. Added --trace-event-loop to identify other blocking calls. 3. Set up event-loop-lag alert at >200ms. 4. Moved heavy crypto to worker_threads pool.",
        "action_plan": "1. Identify blocking calls via --trace-event-loop or clinic.js. 2. Replace sync crypto, fs, zlib calls with async equivalents. 3. Offload CPU-heavy work to worker threads. 4. Add event-loop lag monitoring.",
        "severity": "P1",
        "service_name": "auth-service",
        "category": "application",
        "status": "resolved",
        "error_type": "timeout",
    },
    {
        "incident_no": "INC-2024-0013",
        "title": "Race condition in order status state machine",
        "description": "Orders stuck in 'processing' state after payment confirmation webhook. Payment provider confirmed success but order never transitioned to 'confirmed'. DB shows payment.status='paid' but order.status='processing'. Affects 3% of orders.",
        "root_cause": "Race condition: payment webhook and order timeout-cancel job both read order.status='processing', then each tried to UPDATE to 'confirmed' and 'cancelled' respectively. The job that arrived second won, overwriting the first transition with a lost update.",
        "resolution": "1. Added SELECT ... FOR UPDATE in order status transition to serialize access. 2. Changed to UPDATE orders SET status='confirmed' WHERE status='processing' (compare-and-swap). 3. Added idempotency key on webhook handler. 4. Built reconciliation job to fix stuck orders.",
        "action_plan": "1. Immediate: identify and manually fix stuck orders. 2. Add pessimistic locking on status transitions. 3. Use CAS UPDATE pattern (WHERE current_status = expected). 4. Add idempotency for webhooks. 5. Create reconciliation background job.",
        "severity": "P1",
        "service_name": "order-service",
        "category": "application",
        "status": "resolved",
        "error_type": "race_condition",
    },
    {
        "incident_no": "INC-2024-0014",
        "title": "Memory leak in Python service after 48h uptime",
        "description": "Python (FastAPI) service memory RSS grows from 200MB to 3.5GB over 48h, then gets OOMKilled. Memory profiling with tracemalloc shows top allocation: asyncio.Task objects (2.1M instances). No GC collection of completed tasks.",
        "root_cause": "asyncio.create_task() was called in a request handler without storing the task reference or awaiting it. Python's GC doesn't collect running tasks. Under load, 200 completed-but-unreferenced tasks leaked per second, accumulating 2M tasks over 48h.",
        "resolution": "1. Added TaskSet utility to track spawned tasks and clean up on completion. 2. Set asyncio.Task.add_done_callback to self-remove. 3. Added max-concurrent-tasks semaphore (limit 100). 4. Deploy with --max-requests 10000 + pre-emptive restart at 24h as safety net.",
        "action_plan": "1. Profile memory with tracemalloc. 2. Identify leaked object types (Task, connection, dict). 3. Ensure tasks are cleaned up on completion. 4. Add concurrency limits. 5. Consider pre-emptive restart as safety net.",
        "severity": "P2",
        "service_name": "notification-service",
        "category": "application",
        "status": "resolved",
        "error_type": "OOM",
    },
    {
        "incident_no": "INC-2024-0015",
        "title": "gRPC deadline exceeded on recommendation service",
        "description": "recommendation-service gRPC calls failing with DEADLINE_EXCEEDED. P99 latency 8s (SLO: 300ms). Upstream ML model serving responds in 150ms — delay is NOT in the model. Tracing shows time spent in gRPC layer waiting for connection.",
        "root_cause": "gRPC channel pool was configured with maxConnections=5 but the load balancer was distributing 500 req/s across 5 connections. TCP head-of-line blocking caused later requests on the same connection to wait for earlier slow responses. The slow responses were themselves caused by HOL blocking (vicious cycle).",
        "resolution": "1. Increased maxConnections from 5 to 200 (one per concurrent request). 2. Enabled HTTP/2 max concurrent streams = 1 to prevent HOL at gRPC level. 3. Set keepalive with timeout=10s and permit-keepalive-without-calls. 4. Changed to round_robin LB policy.",
        "action_plan": "1. Check gRPC channel pool size and LB policy. 2. Increase connections per instance. 3. Set max concurrent streams = 1. 4. Tune keepalive settings. 5. Check for HOL blocking via tracing spans.",
        "severity": "P1",
        "service_name": "recommendation-service",
        "category": "application",
        "status": "resolved",
        "error_type": "timeout",
    },
    # ═══ Category: Infrastructure ═══
    {
        "incident_no": "INC-2024-0016",
        "title": "Kubernetes node NotReady — disk pressure",
        "description": "Node ip-10-0-3-45 went NotReady. kubelet logs show 'DiskPressure: available 3%'. Pods on this node being evicted. Node has 100GB EBS, df shows /var/lib/docker 92% full. New pod scheduling failing across the cluster.",
        "root_cause": "Docker image garbage collection threshold was set to 90% but node-slow disk alert was set to 85% (below GC trigger). Old images accumulated during 4 deployments/day without cleanup. Over 2 weeks, unused images consumed 60GB.",
        "resolution": "1. Manually ran docker image prune -a -f to free 55GB. 2. Lowered image GC threshold to 70%. 3. Added kubelet flag --image-gc-high-threshold=70. 4. Added disk usage alert at 75% (above GC but before pressure).",
        "action_plan": "1. Immediate: prune unused Docker images. 2. Check kubelet image GC thresholds. 3. Set GC threshold below alert threshold. 4. Add disk pressure monitoring per node.",
        "severity": "P1",
        "service_name": "k8s-cluster",
        "category": "infrastructure",
        "status": "resolved",
        "error_type": "resource_exhaustion",
    },
    {
        "incident_no": "INC-2024-0017",
        "title": "AWS ECS service unable to place tasks — insufficient memory",
        "description": "ECS service deploy rolling update stuck for 30min. Events log: 'service xxx was unable to place a task because no container instance met all of its requirements'. Cluster all instances at 95%+ memory reservation.",
        "root_cause": "New deployment bumped task memory from 512MB to 1024MB (soft limit). ECS scheduler needs to place new task before draining old one (rolling update). With existing 512MB*8 tasks = 4GB reserved, no instance had 1GB free for the new task.",
        "resolution": "1. Temporarily scaled out cluster by 2 instances via ASG desired count. 2. Let deployment complete. 3. Scaled back in after old tasks drained. 4. Updated capacity planning to account for burst headroom during deployments (1.5x peak).",
        "action_plan": "1. Immediate: add cluster capacity (new instances). 2. Check ECS events for placement failures. 3. Calculate headroom needed for rolling update. 4. Adjust cluster autoscaling to maintain burst buffer. 5. Review per-task memory reservations.",
        "severity": "P1",
        "service_name": "ecs-cluster",
        "category": "infrastructure",
        "status": "resolved",
        "error_type": "resource_exhaustion",
    },
    {
        "incident_no": "INC-2024-0018",
        "title": "Prometheus disk full — time-series database corruption",
        "description": "Prometheus pod crash looping with 'opening storage failed: /prometheus/01H...: invalid magic number 0'. Disk 100% full. TSDB WAL checkpoint corrupted. Monitoring blackout — no metrics for last 20min across entire org.",
        "root_cause": "Cardinality explosion: a new deployment added a label 'request_id' (UUID) to all HTTP metrics. Each unique UUID created a new time series. From 50K to 15M active series in 2h. TSDB WAL grew from 2GB to 50GB, filling the 80GB PVC.",
        "resolution": "1. Restored from last TSDB snapshot (30min data loss). 2. Rolled back deployment that added request_id label. 3. Added relabel_config to drop request_id at scrape time. 4. Set --storage.tsdb.retention.size=60GB. 5. Added cardinality alert at 500K series.",
        "action_plan": "1. Immediate: check disk space, restore from snapshot if corrupted. 2. Identify cardinality spike source (label values). 3. Drop high-cardinality labels. 4. Set retention size limit. 5. Add cardinality + disk alerts.",
        "severity": "P0",
        "service_name": "monitoring",
        "category": "infrastructure",
        "status": "resolved",
        "error_type": "resource_exhaustion",
    },
    {
        "incident_no": "INC-2024-0019",
        "title": "CI/CD pipeline hung on git clone — GitHub rate limit",
        "description": "All CI/CD pipelines stuck at 'git clone' step. Error: 'remote: Repository not found. fatal: Authentication failed...' — but credentials are correct. Started at 14:00 UTC across all pipelines simultaneously.",
        "root_cause": "Organization hit GitHub's secondary rate limit (100 concurrent git operations per org). A scheduled job triggered 200 parallel builds, each doing git clone simultaneously. GitHub returned 429s which the runner interpreted as auth failure.",
        "resolution": "1. Cancelled 150 queued builds to drop below rate limit. 2. Configured git clone --depth=1 to reduce data transfer. 3. Added git cache proxy (git-cache) to serve clones from within VPC. 4. Implemented staggered scheduling (max 50 concurrent clones).",
        "action_plan": "1. Immediate: cancel excessive builds. 2. Check GitHub rate-limit headers. 3. Set up git cache/mirror internally. 4. Implement clone staggering. 5. Use shallow clones where possible.",
        "severity": "P1",
        "service_name": "cicd-pipeline",
        "category": "infrastructure",
        "status": "resolved",
        "error_type": "rate_limit",
    },
    {
        "incident_no": "INC-2024-0020",
        "title": "Terraform state lock timeout blocking all deployments",
        "description": "All terraform apply commands failing with 'Error acquiring the state lock: ConditionalCheckFailedException'. Lock held for 45min. DynamoDB lock table shows lock acquired by a CI run that was terminated by timeout. No heartbeat to release.",
        "root_cause": "CI job (terraform plan) acquired state lock, then exceeded its 30min timeout. The runner was killed but never ran terraform force-unlock. DynamoDB item persisted without TTL. Manual intervention required to delete lock.",
        "resolution": "1. Manually deleted lock item from DynamoDB via AWS Console. 2. Added TTL attribute to lock items (auto-expire after 15min). 3. Reduced terraform plan timeout to 20min. 4. Added pre-kill signal handler (SIGTERM → terraform force-unlock).",
        "action_plan": "1. Immediate: force-unlock or delete lock from DynamoDB. 2. Check who acquired lock and why it stalled. 3. Add TTL to lock table items. 4. Implement graceful unlock on SIGTERM. 5. Set CI timeouts below lock TTL.",
        "severity": "P1",
        "service_name": "infra-tf",
        "category": "infrastructure",
        "status": "resolved",
        "error_type": "deadlock",
    },
    # ═══ Category: Application — additional ═══
    {
        "incident_no": "INC-2024-0021",
        "title": "Kafka consumer lag 50K — notification delay 20min",
        "description": "Kafka consumer group 'notif-push' lag reached 50K messages. P99 notification delivery delay 20min (SLO: 30s). Consumer CPU at 15% — not CPU-bound. No rebalancing in consumer group logs. All partitions assigned. Broker disk IO normal.",
        "root_cause": "Consumer was using synchronous HTTP call to Firebase Cloud Messaging (FCM) inside each message handler. FCM API had intermittent 2s latency on 30% of calls. With 10 consumer threads, effective throughput dropped from 1000 msg/s to 50 msg/s. Messages queued up in Kafka creating the lag.",
        "resolution": "1. Moved FCM push to async via asyncio.ensure_future. 2. Increased consumer threads from 10 to 50. 3. Added circuit breaker with 500ms timeout to FCM calls. 4. Set max.poll.records=100 to reduce per-batch processing time.",
        "action_plan": "1. Check consumer lag: kafka-consumer-groups --describe. 2. Profile handler latency to find bottleneck. 3. Move blocking I/O to async pool. 4. Scale consumer instances horizontally. 5. Add consumer lag alerts >1000.",
        "severity": "P1",
        "service_name": "notification-service",
        "category": "application",
        "status": "resolved",
        "error_type": "timeout",
    },
    {
        "incident_no": "INC-2024-0022",
        "title": "Zero-downtime deploy stuck — health check never passes",
        "description": "Blue-green deployment stuck for 45min. New (green) pods in CrashLoopBackOff: 'readiness probe failed: Get http://10.0.1.45:8080/health: dial tcp 10.0.1.45:8080: connect: connection refused'. Application logs show 'FATAL: password authentication failed for user app_user'. ConfigMap has correct password.",
        "root_cause": "Deployment updated DB password via Kubernetes Secret, but the green pods were using a cached version from /etc/secrets mounted at pod start. The Secret was updated correctly, but pods spawned before the Secret update didn't pick up the new value (Kubernetes does not auto-reload mounted Secrets). Manual rolling restart resolved it.",
        "resolution": "1. Deleted all green pods to force recreation with fresh Secret mount. 2. Added Reloader tool to auto-restart pods on Secret changes. 3. Changed health check from /health (simple port check) to /healthz (validates DB connection). 4. Added deploy hook to verify Secret propagation before green pod creation.",
        "action_plan": "1. Check pod logs for startup errors (kubectl logs -l version=green). 2. Verify Secret is propagated: kubectl get secret -o yaml | grep <key>. 3. Force restart pods if Secret changed. 4. Add Reloader or stakater/Reloader. 5. Change health check endpoint to validate dependencies.",
        "severity": "P1",
        "service_name": "order-service",
        "category": "application",
        "status": "resolved",
        "error_type": "config_error",
    },
    # ═══ Category: Network — additional ═══
    {
        "incident_no": "INC-2024-0023",
        "title": "VPC peering connection dropped — multi-region replication broken",
        "description": "Cross-region VPC peering between us-east-1 and eu-west-1 dropped at 03:00 UTC. MySQL cross-region replication stopped. Replica lag grew to 4GB. DR site out of sync. CloudWatch VPCFlow logs show 'Action: REJECT' for all cross-VPC traffic starting at 02:58 UTC.",
        "root_cause": "Infrastructure-as-code pipeline applied a Terraform change that rebuilt the VPC peering connection with a different CIDR range. The old peering connection was deleted before the new one was fully established (missing create_before_destroy lifecycle rule). A 6-minute window of no connectivity occurred during re-creation.",
        "resolution": "1. Manually accepted the new pending peering connection in AWS Console. 2. Updated route tables in both VPCs to use the new peering connection ID (pcx-xxxxx). 3. Added lifecycle { create_before_destroy = true } to aws_vpc_peering_connection in Terraform. 4. Added AWS Config rule to alert on VPC peering deletion.",
        "action_plan": "1. Verify peering status: aws ec2 describe-vpc-peering-connections. 2. Check route tables in both VPCs. 3. If pending, accept peering manually. 4. Update Terraform with create_before_destroy. 5. Enable VPC Flow Logs alerting on REJECT actions.",
        "severity": "P0",
        "service_name": "infra-network",
        "category": "network",
        "status": "resolved",
        "error_type": "config_error",
    },
    {
        "incident_no": "INC-2024-0024",
        "title": "WebSocket connections dropping every 60s — mobile app reconnect storm",
        "description": "iOS and Android apps experiencing WebSocket disconnects exactly every 60 seconds. Reconnection creates 5000 new connections/second, overloading the WS gateway. Nginx access.log shows 499 status (client closed request) on /ws endpoint. ALB idle timeout set to 60s. WebSocket ping interval set to 120s.",
        "root_cause": "AWS ALB idle timeout was set to 60 seconds (default). Application WebSocket ping/pong interval was 120 seconds. Since no data frames were sent within the 60s idle window when users were just reading content, ALB silently closed the TCP connection. The client-side reconnection logic triggered exactly at the ALB timeout boundary, creating a 1-minute reconnect storm cycle.",
        "resolution": "1. Increased ALB idle timeout to 300s (matching WebSocket max idle). 2. Reduced application WebSocket ping interval to 25s (below 60s ALB threshold). 3. Added exponential backoff jitter to client reconnection (1s, 2s, 4s, 8s, 16s, max 30s). 4. Added WebSocket connection count dashboard with 1min reconnect-rate metric.",
        "action_plan": "1. Check LB idle timeout vs application keepalive/ping interval. 2. Ensure ping interval < LB idle timeout. 3. Add jittered exponential backoff to client reconnects. 4. Monitor reconnect rate as early warning signal.",
        "severity": "P1",
        "service_name": "websocket-gateway",
        "category": "network",
        "status": "resolved",
        "error_type": "timeout",
    },
    # ═══ Category: Security ═══
    {
        "incident_no": "INC-2024-0025",
        "title": "Suspicious spike in failed login attempts — potential brute force",
        "description": "Auth service logging 50K failed login attempts/minute from 340 unique IPs across 12 countries. 99% targeting /api/auth/login with common passwords. Rate limiter configured at 5 req/min per IP — not triggering because attacks are distributed. 3 accounts successfully compromised (confirmed unauthorized orders placed).",
        "root_cause": "Rate limiter was IP-based, but attackers used a distributed botnet with 340 unique IPs. They stayed well below the 5 req/min threshold per IP. No account-level rate limiting was in place. The compromised accounts had no 2FA enabled — they were legacy accounts grandfathered before the 2FA mandate.",
        "resolution": "1. Force-reset passwords for 3 compromised accounts and notified users. 2. Implemented account-level rate limiting (10 failed attempts per account per 5min). 3. Blocked IPs via AWS WAF rate-based rule at 100 req/5min per IP. 4. Forced 2FA enrollment for all accounts without it. 5. Added anomaly detection: login_attempts_from_new_country trigger.",
        "action_plan": "1. Immediate: block attacking IPs in WAF/security group. 2. Force-reset compromised accounts. 3. Implement account-level rate limiting. 4. Audit 2FA coverage — enforce for all accounts. 5. Set up geo-anomaly alerts for login patterns.",
        "severity": "P0",
        "service_name": "auth-service",
        "category": "security",
        "status": "resolved",
        "error_type": "auth_error",
    },
    {
        "incident_no": "INC-2024-0026",
        "title": "S3 bucket public-read ACL applied by misconfigured CI pipeline",
        "description": "Security scanner flagged s3://app-user-uploads with public-read ACL at 16:30 UTC. Bucket contains 2.3M user-uploaded documents including KYC/ID scans (PII). CloudTrail shows PutBucketAcl API call from IAM role 'ci-deployer' at 16:28 UTC. Access logs show 12 anonymous GET requests in the 2-minute exposure window.",
        "root_cause": "A CI pipeline for a static website deployment used a misconfigured Terraform module (terraform-aws-s3-bucket v3.1 with default acl='public-read'). The module was intended for the public assets bucket but was accidentally pointed at the user-uploads bucket via a copy-paste error in the CI variable definition.",
        "resolution": "1. Immediately reverted ACL to private via AWS Console (within 3min of alert). 2. Quarantined the CI pipeline that applied the change. 3. Audited CloudTrail to confirm exactly 12 objects were accessed (none were KYC documents — all were public product images). 4. Added SCP to deny s3:PutBucketAcl with public-read/private. 5. Added AWS Config rule 's3-bucket-public-read-prohibited' with auto-remediation.",
        "action_plan": "1. Immediate: revert ACL to private. 2. Audit CloudTrail for unauthorized access during exposure window. 3. Notify compliance/legal if PII was accessed. 4. Add SCP to block public ACLs org-wide. 5. Add AWS Config auto-remediation rules.",
        "severity": "P0",
        "service_name": "storage-s3",
        "category": "security",
        "status": "resolved",
        "error_type": "config_error",
    },
    # ═══ Category: Application — with different statuses ═══
    {
        "incident_no": "INC-2025-0002",
        "title": "Search latency degrading — investigating Elasticsearch query regression",
        "description": "Search service P95 latency increased from 80ms to 450ms over the last 4 hours. No deployment in that window. No traffic spike observed. Elasticsearch cluster healthy (green, no shard movement). Hot threads show significant time spent in ScriptService for custom scoring script. Index size grew 15% in 4h (normal rate is 2%/day).",
        "severity": "P2",
        "service_name": "search-service",
        "category": "application",
        "status": "investigating",
        "error_type": "timeout",
    },
    {
        "incident_no": "INC-2025-0003",
        "title": "Third-party payment gateway 503 — failover activated",
        "description": "Primary payment gateway (Stripe) returning HTTP 503 on /v1/charges since 11:15 UTC. Failover to secondary gateway (Adyen) activated automatically. Adyen processing 100% of transactions at 3x normal volume. Adyen P99 latency at 800ms (normal: 200ms). Circuit breaker on Stripe still open — retry timer counting down.",
        "root_cause": "Stripe incident confirmed via status.stripe.com — 'Elevated API Errors in us-east-1'. Our circuit breaker (resilience4j) detected 50% failure rate and opened after 100 requests. Failover logic in PaymentRouter correctly redirected to Adyen. Known issue: Adyen not capacity-tested for 100% failover volume.",
        "resolution": "1. Confirmed Stripe incident — our systems operating as designed. 2. Scaled Adyen integration pods from 10 to 30 to handle volume. 3. Added connection pool warming on Adyen side. 4. Monitoring Stripe status page for resolution — will close circuit breaker manually once confirmed.",
        "action_plan": "1. Verify upstream provider status page. 2. Confirm failover is routing correctly. 3. Scale secondary provider if needed. 4. Monitor primary for recovery. 5. Post-incident: capacity-test failover at 100% load.",
        "severity": "P1",
        "service_name": "payment-service",
        "category": "application",
        "status": "mitigated",
        "error_type": "dependency_failure",
    },
    # ═══ Category: Database — additional ═══
    {
        "incident_no": "INC-2024-0027",
        "title": "MongoDB replica set election storm — primary flapping 4x/hour",
        "description": "MongoDB replica set 'rs-orders' experiencing primary re-elections every 15 minutes for the last 3 hours. Each election causes 3-8s write unavailability. Application seeing intermittent MongoTimeoutException on writes. replSetGetStatus shows priority and votes are correctly configured for all 3 members. oplog size adequate at 50GB.",
        "root_cause": "Secondary node in a different AZ had intermittent network packet loss (0.5%) due to a faulty fiber transceiver. The secondary would briefly lose heartbeat (electionTimeoutMillis=10000), triggering an election. It would rejoin, sync, then lose heartbeat again — creating a 15-minute election cycle. The faulty transceiver was not detected by AWS health checks because ping succeeded for 99.5% of packets.",
        "resolution": "1. Forced the faulty secondary to step down (rs.stepDown()) and removed it from the replica set temporarily. 2. AWS replaced the faulty transceiver after we filed a ticket with traceroute evidence. 3. Re-added the node after transceiver replacement. 4. Increased electionTimeoutMillis to 20000 to reduce sensitivity to transient network issues. 5. Added cross-AZ latency and packet-loss monitoring.",
        "action_plan": "1. Check replica set status: rs.status(). 2. Examine node logs for heartbeat timeouts. 3. Isolate faulty node temporarily. 4. Check network health between AZs (packet loss, latency jitter). 5. File ticket with cloud provider if hardware issue.",
        "severity": "P1",
        "service_name": "order-service",
        "category": "database",
        "status": "resolved",
        "error_type": "timeout",
    },
    {
        "incident_no": "INC-2024-0028",
        "title": "Cassandra nodetool repair backlog causing read-repair timeout",
        "description": "Cassandra cluster read latency P99 increased from 15ms to 2.4s. nodetool tpstats shows ReadStage pending=8500. Read repair chance=0.1 but triggered on 80% of reads due to inconsistent replicas. nodetool repair has not been run in 14 days (SLO: 7 days). HintedHandoff queue at 2M pending hints.",
        "root_cause": "Scheduled repair cron job was silently failing for 14 days due to an expired SSL certificate on the JMX connection. nodetool repair could not authenticate. Without regular repairs, replicas diverged, causing read-repair on most reads. Each read-repair is a full read of all replicas + comparison, dramatically increasing read latency.",
        "resolution": "1. Updated JMX SSL certificate and restarted repair cron job. 2. Ran full sequential repair: nodetool repair -full -seq -j 4 on all nodes (took 8h). 3. Reduced read_repair_chance from 0.1 to 0.01 (production guidance). 4. Added monitoring alert: last_repair_time > 7 days. 5. Added a canary repair job that validates JMX connectivity daily.",
        "action_plan": "1. Check last repair time: nodetool repair -pr --dry-run. 2. Run nodetool tpstats to find bottleneck stage. 3. Verify JMX connectivity for repair tool. 4. Run full repair during maintenance window. 5. Add repair monitoring and canary check.",
        "severity": "P1",
        "service_name": "order-service",
        "category": "database",
        "status": "resolved",
        "error_type": "timeout",
    },
    # ═══ Category: Infrastructure — additional ═══
    {
        "incident_no": "INC-2025-0004",
        "title": "Node group scaling stuck — ASG unable to launch new instances",
        "description": "EKS node group 'compute-heavy' failed to scale from 10 to 15 nodes. Pending pods in Unschedulable state. ASG activity history shows 'Launching a new EC2 instance: i-xxxxx. Status Reason: The requested configuration is currently not supported. Launching EC2 instance failed.' CapacityReservation shows no matching reservations.",
        "severity": "P2",
        "service_name": "k8s-cluster",
        "category": "infrastructure",
        "status": "open",
        "error_type": "resource_exhaustion",
    },
    {
        "incident_no": "INC-2024-0029",
        "title": "Artifact repository disk full — npm publish failing",
        "description": "Internal Nexus artifact repository disk usage hit 98%. npm publish commands failing with '413 Request Entity Too Large'. Docker push returning 500 Internal Server Error on /v2/blobs/uploads/. Maven deploy also affected. CI pipelines blocked for all teams. Repository has 500GB EBS volume.",
        "root_cause": "Docker image cleanup policy was set to keep last 10 versions per image. A microservices migration created 200 new Docker repos in 2 weeks (50 microservices × 4 environments). Each image averaging 300MB × 10 versions = 600GB total Docker storage. Combined with 400GB of npm artifacts, total usage exceeded the 500GB volume.",
        "resolution": "1. Manually deleted old Docker images older than 7 days (keep < 5 versions). 2. Updated cleanup policy: keep last 5 Docker images, 3 npm versions. 3. Increased EBS volume to 1TB and expanded filesystem. 4. Divided Nexus into separate blob stores: Docker (750GB) and npm/Maven (250GB). 5. Added disk usage alert at 70% and 85%.",
        "action_plan": "1. Immediate: delete old artifacts to free space. 2. Check cleanup policy settings. 3. Identify largest storage consumers (Docker images usually). 4. Resize volume if needed. 5. Split blob stores by artifact type. 6. Add disk usage monitoring.",
        "severity": "P1",
        "service_name": "artifact-repo",
        "category": "infrastructure",
        "status": "resolved",
        "error_type": "resource_exhaustion",
    },
    # ═══ Category: Application — more variations ═══
    {
        "incident_no": "INC-2024-0030",
        "title": "Memory leak in image processing worker after watermark feature rollout",
        "description": "Image processing workers OOMKilled after 2-3h of uptime following watermark feature deployment. RSS grows linearly at 50MB/min from 200MB to 2GB before OOM. Heap dump analysis shows 1.4M instances of java.awt.image.BufferedImage held in a static ConcurrentHashMap cache. Cache size was supposed to be LRU with max 100 entries but the eviction listener was never registered.",
        "root_cause": "The ImageCache class used a LinkedHashMap with accessOrder=true and a removeEldestEntry override for LRU eviction. However, the Map was wrapped in Collections.synchronizedMap() which doesn't delegate to the LinkedHashMap's removeEldestEntry. The method was never called. The cache grew unbounded, holding every image ever processed by that worker process.",
        "resolution": "1. Replaced Collections.synchronizedMap with Guava Cache (CacheBuilder.maximumSize(100).expireAfterAccess(5, MINUTES)). 2. Added direct memory buffer pool for image processing (MaxDirectMemorySize=512m). 3. Deployed with -XX:+ExitOnOutOfMemoryError to force pod restart on OOM. 4. Set pod memory limit=3Gi with requests=2Gi.",
        "action_plan": "1. Capture heap dump before OOM for analysis. 2. Identify object accumulation pattern (usually in caches or static collections). 3. Check cache eviction logic — ensure LRU/TTL actually works. 4. Consider Guava Cache or Caffeine for robust caching. 5. Set memory limits with graceful degradation.",
        "severity": "P1",
        "service_name": "image-service",
        "category": "application",
        "status": "resolved",
        "error_type": "OOM",
    },
    {
        "incident_no": "INC-2025-0005",
        "title": "API rate limiter misconfiguration — legitimate traffic blocked",
        "description": "Customer reports: mobile app returning '429 Too Many Requests' during normal usage. Rate limiter config was updated 2h ago via feature flag. Current config: X-RateLimit-Limit=10, X-RateLimit-Window=1s. Previously was 100/min. Users seeing error after 2-3 screen transitions. Customer support tickets +200 in last hour.",
        "root_cause": "SRE updated rate limiter via feature flag to mitigate a suspected DDoS. Intended value was 10 requests per second but the configuration UI used a dropdown with 'per second' / 'per minute' options. The value '10 per minute' was selected but the dropdown was misread as 'per second'. The effective limit became 10 requests per minute (previously 100/min) — blocking 90% of legitimate traffic.",
        "severity": "P0",
        "service_name": "api-gateway",
        "category": "application",
        "status": "investigating",
        "error_type": "config_error",
    },
    # ═══ Multi-version ticket — active with history ═══
    {
        "incident_no": "INC-2025-0006",
        "title": "Critical: user data export job leaking PII to logs",
        "description": "Data export job for GDPR compliance started logging full user records (including email, phone, address) to stdout at INFO level. Logs shipped to centralized ELK stack accessible to all engineering. Discovered by security team during routine log audit. Affected records: approximately 47K users over 72 hours of job execution. Export job currently stopped.",
        "root_cause": "DataExportService used Lombok @ToString annotation on the UserRecord model class, which auto-generates a toString() including all fields. The service logged 'Processing record: {}' + record at INFO level. When a developer changed log level from DEBUG to INFO for debugging a separate issue 3 days ago, it was never reverted. The @ToString annotation should have been annotated with @ToString.Exclude on PII fields.",
        "resolution": "1. Immediately stopped the export job and rotated all affected log files. 2. Added @ToString.Exclude annotations on all PII fields in UserRecord (email, phone, address, ssnLast4). 3. Implemented log redaction filter at logback level — pattern-match PII and replace with [REDACTED]. 4. Restricted ELK access to PII-containing indices to security-team only. 5. Conducted mandatory code review for all @ToString-annotated model classes. 6. Added Checkstyle rule to forbid @ToString without explicit @ToString.Exclude on PII fields.",
        "action_plan": "1. Immediate: stop affected job. 2. Identify all log files containing PII — rotate and secure. 3. Audit code for @ToString usage on model classes. 4. Add log-level redaction filter. 5. Restrict log access to PII indices. 6. Add automated PII leak detection in CI pipeline.",
        "severity": "P0",
        "service_name": "data-export-service",
        "category": "security",
        "status": "resolved",
        "error_type": "config_error",
    },
    # ═══ Category: Database — connection/performance ═══
    {
        "incident_no": "INC-2024-0031",
        "title": "MySQL InnoDB deadlock on user_points table during leaderboard update",
        "description": "Leaderboard recalculation cron job failing with 'Deadlock found when trying to get lock; try restarting transaction'. 120K user point updates per minute during peak gaming hours. Deadlock graph shows Transaction A: UPDATE user_points WHERE user_id=1 → waiting on lock held by Transaction B: UPDATE user_points WHERE guild_id=42. Gap lock on secondary index caused by inconsistent WHERE clause ordering across batch operations.",
        "root_cause": "Batch update was ordered by user_id in the cron job but by guild_id in the real-time API. MySQL InnoDB acquired gap locks in different order, creating a circular wait. The guild_id index had a wider gap lock range due to lower cardinality (200 guilds vs 2M users), exacerbating the deadlock probability under concurrent batch + real-time updates.",
        "resolution": "1. Standardized both code paths to UPDATE ... ORDER BY user_id ASC, forcing consistent lock ordering. 2. Reduced batch size from 1000 to 100 rows per transaction to minimize lock hold time. 3. Added deadlock retry with exponential backoff (100ms, 200ms, 400ms, max 5 retries). 4. Created a materialized leaderboard table updated via async queue instead of direct batch UPDATE. 5. Added Percona Toolkit pt-deadlock-logger for continuous deadlock monitoring.",
        "action_plan": "1. Capture deadlock via SHOW ENGINE INNODB STATUS. 2. Analyze lock ordering across all UPDATE paths. 3. Standardize lock order (ORDER BY primary key). 4. Reduce batch sizes to minimize lock scope. 5. Add retry with backoff for deadlock errors. 6. Consider materialized view to decouple read/write.",
        "severity": "P1", "service_name": "game-leaderboard", "category": "database", "status": "resolved", "error_type": "deadlock",
    },
    {
        "incident_no": "INC-2024-0032",
        "title": "DynamoDB hot partition — read throttled on user_activity table",
        "description": "DynamoDB table user_activity experiencing ProvisionedThroughputExceededException on 3 of 50 partitions. Read capacity set to 50000 RCU total but only 1 partition handling 18000 RCU (partition limit is 3000 RCU). Affected partition key: user_id=42 (a community bot account with 2M followers). P99 latency on GetItem increased from 8ms to 2.4s.",
        "root_cause": "Partition key design mistake: used user_id as partition key for a social media activity feed. A platform bot account (user_id=42) had 500x the activity of a normal user, creating a hot partition. DynamoDB's adaptive capacity took 30min to kick in and only doubled the partition limit to 6000 RCU — still not enough for the 18000 RCU demand.",
        "resolution": "1. Added a salt suffix (user_id#0 to user_id#9) to distribute the bot's writes across 10 partition keys. 2. Changed read pattern to use DAX (DynamoDB Accelerator) for read-through caching. 3. Implemented write sharding for known high-traffic user IDs stored in a hot-keys DynamoDB table. 4. Switched to on-demand capacity mode temporarily to absorb the spike. 5. Added CloudWatch alarm on per-partition consumed capacity > 2500 RCU.",
        "action_plan": "1. Identify hot partition via CloudWatch Contributor Insights. 2. Check partition key cardinality — redistribute if skewed. 3. Add salt/sharding for known hot keys. 4. Enable DAX or ElastiCache for read-heavy patterns. 5. Use on-demand capacity temporarily. 6. Add partition-level monitoring and alerts.",
        "severity": "P1", "service_name": "social-feed", "category": "database", "status": "resolved", "error_type": "resource_exhaustion",
    },
    # ═══ Category: Network — more scenarios ═══
    {
        "incident_no": "INC-2024-0033",
        "title": "BGP route hijack causing traffic blackhole for APAC region",
        "description": "Users in APAC (Singapore, Tokyo, Sydney) unable to reach api.example.com. Traffic from APAC being routed to an unrecognized AS (AS64496) in Myanmar. traceroute shows the path exiting via Hong Kong IXP and terminating at an unknown prefix. BGP looking glass confirms route /24 announcement for our IP range from the rogue AS. Other regions (US, EU) unaffected — traffic takes different paths.",
        "root_cause": "A BGP hijack: an ISP in Myanmar (AS64496) accidentally or maliciously announced a more-specific /24 route for our /22 block. Upstream providers in APAC preferred the more-specific route, redirecting traffic. Our /22 announcement from our own AS (AS16509) was still visible but less specific and therefore not preferred. The hijack lasted 47 minutes until the upstream ISP detected the anomaly and applied a prefix filter.",
        "resolution": "1. Contacted upstream ISP (NTT) to apply prefix filter — resolved within 47min of detection. 2. Registered ROA (Route Origin Authorization) in all 5 RIRs for our IP blocks. 3. Implemented RPKI validation with our upstreams to reject invalid BGP announcements. 4. Added BGP monitoring via ThousandEyes to detect route changes globally. 5. Created an incident response runbook for BGP hijack scenarios with contact numbers for all upstream ISPs.",
        "action_plan": "1. Confirm hijack via BGP looking glass (Hurricane Electric, RIPE RIS). 2. Contact upstream ISP immediately to filter rogue announcements. 3. Register ROA for all IP blocks in RIRs. 4. Enable RPKI validation on all peering sessions. 5. Set up BGP monitoring and alerting. 6. Prepare press/status-page communication for extended outages.",
        "severity": "P0", "service_name": "infra-network", "category": "network", "status": "resolved", "error_type": "config_error",
    },
    # ═══ Category: Application — complex debugging ═══
    {
        "incident_no": "INC-2024-0034",
        "title": "JVM metaspace leak — Full GC every 3min after Java 17 upgrade",
        "description": "After upgrading from Java 11 to 17, 4 of 12 JVM instances showing Full GC every 3min with Metaspace at 98% (256MB max). GC logs show 'Full GC (Metadata GC Threshold)' triggered because Metaspace usage approaching MaxMetaspaceSize. Classes loaded: 185000 (up from 12000 on Java 11). Heap usage healthy at 40%. No memory leak in heap — purely metaspace exhaustion.",
        "root_cause": "Java 17 changed the default ReflectionFactory behavior, re-enabling reflection-based access to methods previously optimized away. Spring Boot 2.7 with Hibernate 5.6 triggered massively more reflective access under Java 17, generating 170K+ synthetic proxy classes. The ClassLoader retained references to all generated classes, preventing Metaspace reclamation via the ClassUnloading GC cycle.",
        "resolution": "1. Increased MaxMetaspaceSize from 256m to 512m (short-term mitigation). 2. Upgraded Spring Boot from 2.7 to 3.1 (native Java 17 support with optimized reflection). 3. Disabled Hibernate bytecode enhancement which was generating excessive proxy classes. 4. Added JVM flag -XX:MaxMetaspaceExpansion=64m to slow metaspace growth rate. 5. Set up Metaspace monitoring alert at 75% with trend analysis.",
        "action_plan": "1. Analyze class loading: jcmd <pid> VM.classloader_stats. 2. Identify which library is generating excessive classes (reflection proxies are common). 3. Increase MaxMetaspaceSize as short-term fix. 4. Upgrade libraries to versions with native Java 17 support. 5. Add Metaspace monitoring with trend-based alerting. 6. Consider -XX:+UnlockDiagnosticVMOptions -XX:+PrintClassHistogram for debugging.",
        "severity": "P1", "service_name": "payment-service", "category": "application", "status": "resolved", "error_type": "OOM",
    },
    {
        "incident_no": "INC-2024-0035",
        "title": "Distributed lock timeout — idempotency key collision on payment retry",
        "description": "Payment processing service creating duplicate charges. 23 customers double-charged in 45min window. Idempotency key design: SHA256(user_id + amount + timestamp_truncated_to_minute). Customer initiated retry exactly at the minute boundary, generating the same idempotency key for two different intent IDs. First charge succeeded, second retry bypassed the idempotency check because the first charge had released the Redis lock before the second check.",
        "root_cause": "Three bugs compounded: (1) Timestamp truncated to minute in idempotency key — retry within same minute produced identical key. (2) Redis distributed lock TTL was 5s but payment gateway timeout was 10s — lock expired before the first charge's response was received, allowing the second request to acquire the lock. (3) Idempotency check used cache-aside pattern: check Redis → not found → process → store in Redis. Race condition between 'not found' check and 'store' step allowed duplicated processing.",
        "resolution": "1. Immediately refunded 23 double-charged customers with apology credit. 2. Changed idempotency key to include a monotonic retry counter: SHA256(user_id + amount + retry_count). 3. Increased Redis lock TTL to 30s (above gateway timeout + safety margin). 4. Replaced cache-aside with write-through: SETNX before processing, store result after. 5. Added idempotency audit log table in DB for post-hoc verification. 6. Implemented reconciliation job to detect and flag duplicate charges within 5min.",
        "action_plan": "1. Stop processing — investigate duplicate charge reports immediately. 2. Refund all affected customers. 3. Fix idempotency key to include retry counter. 4. Increase lock TTL above worst-case processing time. 5. Use SETNX atomic operation instead of check-then-set. 6. Add reconciliation monitoring for duplicate transactions.",
        "severity": "P0", "service_name": "payment-service", "category": "application", "status": "resolved", "error_type": "race_condition",
    },
    # ═══ Category: Infrastructure — more scenarios ═══
    {
        "incident_no": "INC-2024-0036",
        "title": "AWS EBS volume performance baseline exhausted — gp2 to gp3 migration",
        "description": "After migrating 200 EBS volumes from gp2 to gp3, 12 RDS instances experienced severe IOPS throttling. gp3 baseline is 3000 IOPS (gp2 was dynamic based on volume size). The migrated 100GB gp3 volumes had 3000 IOPS baseline but the database workload required 8000 IOPS. CloudWatch showed EBS VolumeQueueLength > 10 and VolumeThroughputPercentage at 100%. RDS BurstBalance dropped to 0% within 30min of migration.",
        "root_cause": "gp3 provides fixed 3000 IOPS baseline with burst up to 16000, but sustained IOPS above baseline depletes burst credits. gp2 provided 3 IOPS per GB (100GB = 300 IOPS baseline with burst to 3000). The DBA team had been relying on gp2 burst mode to handle peak loads without realizing it. When migrating to gp3, they set provisioned IOPS to 3000 (match gp2 burst) but this was consumed as baseline, with additional burst credits depleting quickly under sustained 8000 IOPS load.",
        "resolution": "1. Immediately increased provisioned IOPS to 12000 on the 12 affected volumes (gp3 supports up to 16000). 2. Analyzed CloudWatch IOPS metrics for all 200 migrated volumes — identified 31 volumes needing IOPS increase. 3. Created an IOPS calculator script that queries CloudWatch metrics and recommends gp3 provisioned IOPS based on P95 usage. 4. Added CloudWatch alarm: BurstBalance < 20% for any EBS volume. 5. Updated migration runbook to require 7-day CloudWatch analysis before gp2→gp3 migration.",
        "action_plan": "1. Check EBS BurstBalance and VolumeQueueLength for affected volumes. 2. Increase gp3 provisioned IOPS to P95 + 30% headroom. 3. Audit all recently migrated volumes for IOPS adequacy. 4. Create pre-migration IOPS analysis script. 5. Add BurstBalance alarm below 20%. 6. Update migration runbook.",
        "severity": "P0", "service_name": "data-platform", "category": "infrastructure", "status": "resolved", "error_type": "resource_exhaustion",
    },
    {
        "incident_no": "INC-2024-0037",
        "title": "Docker daemon unresponsive — containerd snapshot leak after 30 days",
        "description": "Docker daemon on 8 build agents became unresponsive: docker ps hangs, docker build times out. Systemd journal shows 'containerd: failed to create shim task: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: \"runc\": executable file not found in $PATH'. Host disk usage at 85%. /var/lib/containerd/io.containerd.snapshotter.v1.overlayfs taking 420GB.",
        "root_cause": "CI pipeline used dockerd --rm flag in docker run but the cleanup relied on the container process exiting normally. When builds were killed by CI timeout (BUILD_TIMEOUT=15min), the runc shim was SIGKILL'd but the containerd snapshot was not cleaned up. Over 30 days, 14000 orphaned snapshots accumulated consuming 420GB. The disk fill caused containerd to fail to spawn new shims because /tmp was on the same partition.",
        "resolution": "1. Manually pruned orphaned snapshots: containerd snapshot prune and docker system prune -af. 2. Added a daily cron job: docker system prune -af --filter 'until=24h' for build agents. 3. Moved containerd root to a separate 500GB partition (/var/lib/containerd) from OS disk. 4. Added disk usage alert at 70% with automated prune at 80%. 5. Set CI_BUILD_CLEANUP timeout 5min longer than BUILD_TIMEOUT to guarantee cleanup window.",
        "action_plan": "1. Check disk usage: df -h /var/lib/containerd. 2. Prune orphaned snapshots with containerd snapshot prune. 3. Run docker system prune -af. 4. Add daily cleanup cron job. 5. Separate containerd root to distinct partition. 6. Add disk usage alerting and auto-prune at threshold.",
        "severity": "P1", "service_name": "ci-build-agents", "category": "infrastructure", "status": "resolved", "error_type": "resource_exhaustion",
    },
    # ═══ Category: Security — more scenarios ═══
    {
        "incident_no": "INC-2024-0038",
        "title": "Secrets leaked via .env file committed to public GitHub repository",
        "description": "GitGuardian alert: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and DATABASE_URL found in public GitHub repo example-app/.env at commit a3f8c12. The keys were for a production IAM user with AdministratorAccess policy. AWS CloudTrail shows the keys were not used externally (good) but the exposure window was 4 hours. The repository had 34 external forks (some by unknown users). Commit author: intern who was testing a local setup script.",
        "root_cause": "Intern added .env.example to the repository but accidentally also committed .env (which was in .gitignore on main branch but not on the feature branch they created). The pre-commit hook (git-secrets) was configured only on main branch. The AWS keys were production-level credentials left in the intern's local env from an onboarding script that should have used temporary credentials.",
        "resolution": "1. Immediately rotated all exposed AWS keys via IAM console — new keys generated within 6min of alert. 2. Force-pushed amended commit with .env removed and purged from git history using git filter-branch + BFG Repo-Cleaner. 3. Contacted GitHub Support to remove the commit from all 34 forks (GitHub policy covers this). 4. Applied git-secrets hook globally via .gitconfig core.hooksPath instead of per-branch. 5. Added .env to global gitignore via git config --global core.excludesFile. 6. Created onboarding script that issues temporary IAM credentials with 8h expiry instead of long-lived keys. 7. Added GitHub Advanced Security secret scanning with push protection.",
        "action_plan": "1. Rotate exposed credentials IMMEDIATELY. 2. Audit CloudTrail for unauthorized access during exposure window. 3. Remove secret from git history with BFG Repo-Cleaner. 4. Contact GitHub to remove from forks. 5. Enforce git-secrets globally. 6. Switch to temporary credentials for development. 7. Enable push-protection secret scanning.",
        "severity": "P0", "service_name": "infra-secrets", "category": "security", "status": "resolved", "error_type": "config_error",
    },
    # ═══ Category: Database — more ═══
    {
        "incident_no": "INC-2024-0039",
        "title": "PostgreSQL autovacuum lag causing table bloat — query planner degradation",
        "description": "PostgreSQL orders table grew from 50GB to 180GB in 2 weeks without corresponding data growth. pg_stat_user_tables shows n_dead_tup = 80M (45% of total rows), last_autovacuum = 3 days ago. Autovacuum configured with default scale factor (20%) but the table's 80M dead tuples represent 45% bloat. Query planner switching from Index Scan to Seq Scan because pg_class.relpages inflated — queries went from 15ms to 3.2s P99. Application experiencing intermittent timeouts.",
        "root_cause": "A new 'archive orders' feature used UPDATE orders SET archived = true WHERE created_at < '...' which touched 200M historical rows. Each UPDATE created a dead tuple. Autovacuum trigger threshold = autovacuum_vacuum_scale_factor(0.2) * 200M = 40M dead tuples before triggering. But the UPDATE was batch-committed in 10M-row chunks, each leaving dead tuples. By the time autovacuum triggered at 40M, there were already 80M dead tuples and 130GB of bloat. Autovacuum couldn't keep up because it was I/O throttled by autovacuum_vacuum_cost_limit=200 (default).",
        "resolution": "1. Manually ran VACUUM FULL orders (took 4h, exclusive lock — scheduled maintenance window). 2. Reduced autovacuum_vacuum_scale_factor from 0.2 to 0.05 for large tables (>10GB). 3. Set per-table storage parameters: ALTER TABLE orders SET (autovacuum_vacuum_scale_factor = 0.01, autovacuum_vacuum_cost_limit = 2000). 4. Changed archive pattern to use INSERT INTO orders_archive SELECT ... followed by DELETE (creates fewer dead tuples than bulk UPDATE). 5. Added pgstattuple monitoring to detect bloat early. 6. Scheduled weekly VACUUM ANALYZE for all tables >50GB.",
        "action_plan": "1. Check table bloat: SELECT schemaname, relname, n_dead_tup, n_live_tup, round(n_dead_tup*100.0/(n_live_tup+1),2) as dead_ratio FROM pg_stat_user_tables ORDER BY dead_ratio DESC. 2. Analyze query plans: EXPLAIN ANALYZE on slow queries. 3. Adjust autovacuum scale factor for large tables. 4. Run VACUUM FULL during maintenance window if bloat > 20%. 5. Change bulk UPDATE patterns to INSERT+DELETE. 6. Add bloat monitoring and trend alerts.",
        "severity": "P1", "service_name": "order-service", "category": "database", "status": "resolved", "error_type": "timeout",
    },
    {
        "incident_no": "INC-2024-0040",
        "title": "Redis Cluster resharding stuck — slot migration causing CLUSTERDOWN",
        "description": "Redis Cluster with 6 nodes (3 master, 3 replica) in CLUSTERDOWN state during reshard operation. CLUSTER NODES shows epoch=15 for slots 0-5460 on master-1 but epoch=16 for the same slots on master-2 (split-brain). The reshard command (redis-cli --cluster reshard) was killed mid-operation by CI timeout. 4000 of 16384 slots stuck in migrating/importing state. Clients receiving MOVED and ASK redirections in a loop.",
        "root_cause": "CI pipeline running redis-cli --cluster reshard had a 10min timeout. Slot migration for 4000 slots over a slow network (cross-AZ, 2ms latency) requires approximately 15min at 5 slots/second. The pipeline killed the reshard process at 10min, leaving 1200 slots in MIGRATING state (source node) and IMPORTING state (target node). The CLUSTER NODES config epoch mismatch occurred because the target node incremented its epoch but the source node didn't confirm before the process was killed.",
        "resolution": "1. Manually completed slot migration: CLUSTER SETSLOT <slot> NODE <target-node-id> for each of the 1200 stuck slots via a script. 2. Verified cluster health with redis-cli --cluster check. 3. Increased CI timeout from 10min to 30min for cluster operations. 4. Added --cluster-yes flag to skip interactive prompts and --timeout 30000 for migration timeout. 5. Changed reshard approach to migrate 100 slots at a time with verification checkpoints between batches. 6. Added Redis Cluster health check monitoring with CLUSTER INFO > state_ok alert.",
        "action_plan": "1. Check cluster state: redis-cli CLUSTER INFO and CLUSTER NODES. 2. Identify stuck slots: CLUSTER SLOTS. 3. Manually set slot ownership if stuck: CLUSTER SETSLOT <slot> NODE <node-id>. 4. Verify cluster health after fix. 5. Increase CI timeout for cluster operations. 6. Implement incremental migration with checkpoint verification.",
        "severity": "P0", "service_name": "session-service", "category": "database", "status": "resolved", "error_type": "deadlock",
    },
    # ═══ Category: Application — edge cases ═══
    {
        "incident_no": "INC-2024-0041",
        "title": "JWT signing key rotation causes mass logout — 2M users affected",
        "description": "Scheduled JWT signing key rotation at 02:00 UTC caused all existing session tokens to become invalid. 2M active users unexpectedly logged out. Login service returning HTTP 401 for all requests with existing tokens. New logins working correctly — only existing sessions affected. Key rotation script fetched new key from AWS KMS but did not retain the old key for a grace period. Token validation failed because the old key was no longer in the JWKS endpoint.",
        "root_cause": "JWT validation used a single active signing key. The rotation script: (1) generated new key in KMS, (2) updated JWKS endpoint with new key only, (3) deleted old key from KMS. The script had no 'acceptance period' where both old and new keys are valid simultaneously. Industry standard for JWT rotation: publish new key in JWKS at T-1h, start signing with new key at T+0, stop accepting old key at T+24h.",
        "resolution": "1. Re-imported the old KMS key from backup and published it alongside the new key in JWKS (both keys now valid). 2. All 2M sessions recovered automatically as clients re-authenticated within 10min. 3. Rewrote rotation script to follow 3-phase protocol: phase 1 (T-1h: publish new key), phase 2 (T+0: sign with new key), phase 3 (T+24h: remove old key). 4. Added validation: script refuses to delete the ONLY active key. 5. Added monitoring alert: 401 error rate > 10% triggers on-call. 6. Created a canary token that is validated every 60s to detect JWKS misconfiguration before user impact.",
        "action_plan": "1. Restore old key immediately and publish both in JWKS. 2. Update rotation script to support overlapping key validity. 3. Never delete the only active key. 4. Add 401 rate monitoring and alerting. 5. Implement canary token validation. 6. Document key rotation runbook with rollback procedure.",
        "severity": "P0", "service_name": "auth-service", "category": "application", "status": "resolved", "error_type": "config_error",
    },
    # ═══ Category: Infrastructure — network/cloud ═══
    {
        "incident_no": "INC-2024-0042",
        "title": "AWS us-east-1 AZ-a partial power loss — cross-AZ failover latency",
        "description": "AWS us-east-1 AZ-a experienced a partial power event at 06:15 UTC. Our ELB health checks began failing for 15 instances in AZ-a. Auto Scaling Group started launching replacement instances but they were placed in AZ-a (not spread across AZs) because the ASG had no AZRebalance suspension. New instances also failed. Cross-AZ failover worked for stateless services (via Route53) but stateful services (Kafka brokers, Redis nodes) took 12min to manually failover because they required sequential leader re-election.",
        "root_cause": "(1) ASG did not have AZRebalance process suspended — when launching replacements for AZ-a failures, ASG tried to rebalance across AZs, placing new instances back into the failed AZ. (2) Stateful service failover required manual intervention because automation was disabled after a previous false-positive failover caused data loss. (3) The decision to disable automated failover was documented in a runbook but the runbook was 6 months out of date — the new Kafka cluster topology required a different failover sequence.",
        "resolution": "1. Suspended AZRebalance on all ASGs (aws autoscaling suspend-processes --scaling-processes AZRebalance). 2. Manually failed over stateful services: Kafka partition reassignment (kafka-reassign-partitions), Redis CLUSTER FAILOVER. 3. Updated runbook with current topology and automated the failover with pre-flight checks (validate ISR counts before promoting replicas). 4. Added cross-AZ instance distribution monitoring: alert if >60% instances in single AZ. 5. Scheduled quarterly runbook review and dry-run failover tests.",
        "action_plan": "1. Immediately suspend ASG AZRebalance to prevent placement in failed AZ. 2. Check service health per AZ — evacuate affected AZ. 3. Manually failover stateful services following updated runbook. 4. Add cross-AZ distribution monitoring. 5. Automate stateful failover with safety checks. 6. Schedule quarterly failover dry-runs and runbook updates.",
        "severity": "P0", "service_name": "infra-platform", "category": "infrastructure", "status": "resolved", "error_type": "dependency_failure",
    },
    # ═══ Category: Application — language-specific ═══
    {
        "incident_no": "INC-2024-0043",
        "title": "Go routine leak — goroutine count 120K after new feature rollout",
        "description": "Go service goroutine count increased from 200 to 120K over 6 hours after deploying v3.2.0. /debug/pprof/goroutine?debug=1 shows 115K goroutines blocked on chan receive at notification.go:87. Memory RSS grew from 200MB to 8GB (mostly goroutine stacks). CPU at 12% — not CPU-bound. OOMKiller terminated the process when RSS exceeded pod limit of 10GB.",
        "root_cause": "v3.2.0 added a fire-and-forget pattern: go sendNotification(userID) inside the CreateOrder handler without tracking the goroutine lifecycle. sendNotification had a channel send operation: resultCh <- resp that was received by a single consumer goroutine. The consumer was rate-limited to 100 req/s against the push notification API. Under 5000 orders/s, goroutines accumulated at 5000/s creation vs 100/s completion, leaking 4900 goroutines per second.",
        "resolution": "1. Rolled back to v3.1.0. 2. Replaced fire-and-forget goroutines with a buffered channel worker pool (100 workers, channel capacity 1000). 3. Added goroutine count monitoring: alert > 10000 goroutines for > 5min. 4. Set GOMAXPROCS to match CPU limits and added debug.SetMaxThreads(10000) to crash early instead of OOM. 5. Added lint rule (go vet + custom analyzer) to flag 'go func' calls without lifecycle management (errgroup or worker pool).",
        "action_plan": "1. Check goroutine count via /debug/pprof/goroutine. 2. Identify blocking point: analyze blocked goroutine stacks. 3. Replace fire-and-forget with worker pools or errgroup. 4. Add goroutine count monitoring and alerting. 5. Set Go runtime limits (SetMaxThreads). 6. Add lint rules for unmanaged goroutines.",
        "severity": "P0", "service_name": "order-service", "category": "application", "status": "resolved", "error_type": "OOM",
    },
    {
        "incident_no": "INC-2024-0044",
        "title": "Python asyncio event loop blocked by synchronous DB call in async handler",
        "description": "FastAPI async endpoint /api/reports/generate taking 45s to respond (expected < 2s). Event loop blocked for 42s on a single synchronous call: psycopg2 (sync driver) conn.execute() inside an async def handler. Other endpoints on the same worker process unresponsive during the block. Uvicorn worker timeout killed the request at 30s but the DB query continued running on the server side, holding a connection from the pool.",
        "root_cause": "Developer used psycopg2 (synchronous driver) instead of asyncpg or psycopg3 (async) inside an async def handler: result = conn.execute(query). The synchronous call blocked the entire event loop for its duration (42s for a reporting query on 200M rows). Other requests to the same worker were queued but not processed. Under 50 concurrent requests, all 4 uvicorn workers were blocked, causing 504 Gateway Timeout for all new requests.",
        "resolution": "1. Replaced psycopg2 with asyncpg for all async handlers: result = await pool.fetch(query). 2. Moved the heavy reporting query to a background task (Celery) with a polling endpoint for results. 3. Added a sync-vs-async lint rule: detect synchronous DB calls in async functions. 4. Set uvicorn --limit-concurrency 100 to queue excess requests instead of blocking workers. 5. Added event loop latency monitoring with asyncio.get_event_loop().slow_callback_duration.",
        "action_plan": "1. Identify blocking calls: enable asyncio debug mode or use py-spy. 2. Replace sync DB drivers with async equivalents (asyncpg, databases, SQLAlchemy async). 3. Move heavy queries to background task queue. 4. Add lint rules to detect sync-in-async patterns. 5. Add event loop latency monitoring. 6. Set concurrency limits to prevent worker saturation.",
        "severity": "P1", "service_name": "reporting-service", "category": "application", "status": "resolved", "error_type": "timeout",
    },
]


def seed():
    Base.metadata.create_all(engine)
    print("Tables created (if not existed).")

    ids = ingest_tickets_batch(SEED_TICKETS)
    print(f"Seeded {len(ids)} tickets:")
    for i, tid in enumerate(ids):
        print(f"  [{i+1}] {tid}")
    print("Done.")


if __name__ == "__main__":
    seed()
