"""
Generate realistic mock incident tickets for PoC validation.

Run:  python seed_data.py
"""

from db import ingest_tickets_batch
from models import Base, engine

SEED_TICKETS = [
    # ═══ Category: Database ═══
    {
        "incident_no": "INC-2024-0001",
        "title": "MySQL master CPU 100% after traffic spike",
        "description": "mysql-master-01 CPU hit 100% at 14:32 UTC. Replication lag grew to 45s on slave-01. Application error rate spiked to 12%. Slow query log shows 10x increase in SELECT * FROM orders WHERE status='pending'.",
        "root_cause": "Missing composite index on (user_id, status) caused full-table scan of 8M-row orders table during a promotion campaign. Connection pool exhausted as each query took 8s instead of 50ms.",
        "resolution": "1. Added composite index CREATE INDEX idx_orders_user_status ON orders(user_id, status). 2. Set max_execution_time=2000 on the session pool. 3. Scaled read-replicas from 2 to 4 temporarily. Index brought query time down to 40ms.",
        "action_plan": "1. Immediate: kill long-running queries, enable query cache. 2. Analyze slow-query-log to identify missing indexes. 3. Add index, verify EXPLAIN plan. 4. Scale replicas if needed. 5. Set up slow-query alerting.",
        "severity": "P0",
        "service_name": "order-service",
        "category": "database",
        "status": "resolved",
        "error_type": "timeout",
    },
    {
        "incident_no": "INC-2024-0002",
        "incident_no": "INC-2024-0002",
        "title": "PostgreSQL connection pool exhausted during black-friday",
        "description": "PG connection pool maxed out at 500 connections. New requests failing with 'FATAL: sorry, too many clients already'. Latency p99 went from 80ms to 12s. HikariCP metrics show active connections stuck at max for 20min.",
        "root_cause": "A new deployment introduced N+1 queries in the product-listing endpoint. Each page view spawned 200+ individual queries instead of 1 JOIN. Connection pool drained in 3min under peak traffic.",
        "resolution": "1. Rolled back deployment to previous version. 2. Rewrote product-listing query to use a single JOIN with eager loading. 3. Increased pool size from 50 to 150 per instance. 4. Added pgbouncer transaction pooling.",
        "action_plan": "1. Immediate: rollback deployment if recent, else kill idle connections. 2. Check pg_stat_activity for query patterns. 3. Identify N+1 patterns in application code. 4. Add pgbouncer. 5. Set connection timeout to 10s.",
        "severity": "P0",
        "service_name": "product-service",
        "category": "database",
        "status": "resolved",
        "error_type": "timeout",
    },
    {
        "incident_no": "INC-2024-0003",
        "title": "Redis cluster OOM evicting keys under load",
        "description": "Redis cluster nodes started evicting keys due to maxmemory limit. Cache hit rate dropped from 98% to 23% within 5min. Backend MySQL read QPS jumped 15x causing cascading latency.",
        "root_cause": "Background job updated 2M user session entries with TTL=0 (no expiry), saturating Redis memory. Eviction policy was allkeys-lru, so hot cache keys were evicted, exposing bare DB.",
        "resolution": "1. Manually set TTL on oversized keys via SCAN+EXPIRE. 2. Changed eviction policy to volatile-lru. 3. Added memory monitoring with 80% threshold alert. 4. Set maxmemory-policy noeviction for session keys.",
        "action_plan": "1. Immediate: identify and expire bloated keys. 2. Check INFO memory and MONITOR for write patterns. 3. Switch eviction policy if needed. 4. Add memory alerts at 70%/85%. 5. Audit all code paths that SET without TTL.",
        "severity": "P1",
        "service_name": "session-service",
        "category": "database",
        "status": "resolved",
        "error_type": "OOM",
    },
    {
        "incident_no": "INC-2024-0004",
        "title": "Deadlock on inventory deduction during flash sale",
        "description": "Multiple concurrent transactions deadlocking on inventory UPDATE. Error log shows 'Deadlock found when trying to get lock; try restarting transaction'. 40% of checkout attempts failed.",
        "root_cause": "Inventory deduction logic used SELECT ... FOR UPDATE on item_id then UPDATE on warehouse_id in different order across two code paths (order vs. refund). Inconsistent lock ordering caused deadlock.",
        "resolution": "1. Standardized lock ordering: always lock warehouse first, then item. 2. Wrapped both UPDATEs in a single CTE to reduce lock duration. 3. Added retry with exponential backoff in application layer.",
        "action_plan": "1. Immediate: restart stuck transactions via pg_terminate_backend. 2. Capture deadlock logs from pg_stat_activity. 3. Audit lock ordering in all inventory code paths. 4. Add retry logic. 5. Consider optimistic locking via version column.",
        "severity": "P0",
        "service_name": "inventory-service",
        "category": "database",
        "status": "resolved",
        "error_type": "deadlock",
    },
    {
        "incident_no": "INC-2024-0005",
        "title": "Elasticsearch cluster red status — unassigned shards",
        "description": "ES cluster went red after node-03 was terminated by OOM killer. 12 primary shards unassigned. Search API returning 503 for 30% of queries. Indexing rate dropped to zero.",
        "root_cause": "Node-03 held 12 primary shards with replica=0. Node crash left shards unassigned with no replica to promote. OOM was caused by a bulk reindex job that allocated 8GB heap, exceeding the 4GB Xmx limit.",
        "resolution": "1. Used _cluster/reroute to allocate stale primary shards (accept_data_loss=true, since replicas already 0). 2. Increased heap to 8GB with proper Xmx/Xms alignment. 3. Set replica=1 for all critical indices.",
        "action_plan": "1. Immediate: reroute unassigned shards. 2. Check _cluster/health and _cat/shards. 3. Ensure all indices have >=1 replica. 4. Review JVM heap config. 5. Add disk watermark alerts.",
        "severity": "P0",
        "service_name": "search-service",
        "category": "database",
        "status": "resolved",
        "error_type": "OOM",
    },
    # ═══ Category: Network ═══
    {
        "incident_no": "INC-2024-0006",
        "title": "Intermittent 502 errors between API gateway and upstream",
        "description": "API gateway logging intermittent 502 Bad Gateway errors (5% of requests). Upstream health checks passing. No error in upstream application logs. tcpdump shows RST packets during affected windows. Duration: 3min bursts every 15min.",
        "root_cause": "AWS NLB idle timeout was set to 350s. Application keepalive was 360s. During low traffic, connections idled past NLB timeout and were silently dropped. Next request on the stale connection got RST, returning 502.",
        "resolution": "1. Set application keepalive to 300s (below NLB's 350s). 2. Enabled connection pooling with TTL=240s. 3. Added retry with backoff on 502 in gateway config. 502 rate dropped to 0%.",
        "action_plan": "1. Check load-balancer idle timeout vs application keepalive. 2. Capture packet trace for RST analysis. 3. Adjust keepalive to be LOWER than LB timeout. 4. Add health-check interval tuning.",
        "severity": "P1",
        "service_name": "api-gateway",
        "category": "network",
        "status": "resolved",
        "error_type": "timeout",
    },
    {
        "incident_no": "INC-2024-0007",
        "title": "DNS resolution failures causing cascading service outages",
        "description": "Multiple services reporting UnknownHostException. /etc/resolv.conf shows correct nameservers. dig commands timeout intermittently. Affected: payment-service, notification-service, user-service. Impact: 25% of transactions failing.",
        "root_cause": "CoreDNS pods in k8s cluster were hitting their 9984-concurrent-request limit. A new deployment of 50 pods simultaneously sent DNS queries at startup, creating a thundering-herd effect. CoreDNS autoscaler was misconfigured with min=1.",
        "resolution": "1. Scaled CoreDNS to 5 replicas. 2. Set podAntiAffinity to spread across nodes. 3. Added ndots:2 to resolv.conf to reduce query volume. 4. Adjusted CoreDNS autoscaler to min=3 with CPU threshold 60%.",
        "action_plan": "1. Immediate: scale DNS replicas. 2. Check DNS query rate and latency. 3. Verify CoreDNS autoscaler config. 4. Review ndots setting in resolv.conf. 5. Consider node-local DNS cache.",
        "severity": "P0",
        "service_name": "infra-dns",
        "category": "network",
        "status": "resolved",
        "error_type": "timeout",
    },
    {
        "incident_no": "INC-2024-0008",
        "title": "TLS certificate expiry causing HTTPS connection failures",
        "description": "prod.example.com TLS certificate expired at 00:00 UTC. All HTTPS connections rejected with SSL_ERROR_EXPIRED_CERTIFICATE. Users unable to login. Mobile app returning network error on all endpoints.",
        "root_cause": "Let's Encrypt auto-renewal cron job on certbot was silently failing for 30 days due to incorrect IAM role permission change on Route53 DNS validation. Manual renewal had not been performed.",
        "resolution": "1. Manually renewed cert via certbot --force-renewal. 2. Restarted nginx to pick up new cert. 3. Fixed IAM role to allow route53:ChangeResourceRecordSets. 4. Added Prometheus alert for cert_expiry_days < 14.",
        "action_plan": "1. Immediate: manual cert renewal + reload. 2. Verify expiry dates via openssl s_client. 3. Check auto-renewal logs. 4. Fix IAM perms if using DNS challenge. 5. Add cert monitoring + alerting.",
        "severity": "P0",
        "service_name": "api-gateway",
        "category": "network",
        "status": "resolved",
        "error_type": "auth_error",
    },
    {
        "incident_no": "INC-2024-0009",
        "title": "Kubernetes service mesh sidecar memory leak",
        "description": "Envoy sidecars across 3 services showing steady RSS growth from 200MB to 2GB over 6h. Nodes running out of allocatable memory. OOMKiller terminating sidecars causing traffic disruption.",
        "root_cause": "Envoy 1.26.0 had a known memory leak in the ext_authz filter when upstream auth service returns 5xx. Each failed auth request leaked ~2KB. With 100 auth failures/s over 6h = ~4GB leaked total.",
        "resolution": "1. Upgraded Envoy sidecar from 1.26.0 to 1.26.4 (leak fixed). 2. Added sidecar memory limit of 512Mi with OOM score adjustment. 3. Set ext_authz failure_mode_allow to false to fail closed. 4. Put circuit breaker on auth service to return 429 at 80% capacity.",
        "action_plan": "1. Immediate: restart leaking sidecars. 2. Identify Envoy version, check release notes. 3. Upgrade if known leak. 4. Add memory limits per sidecar. 5. Set up sidecar memory monitoring.",
        "severity": "P1",
        "service_name": "istio-mesh",
        "category": "network",
        "status": "resolved",
        "error_type": "OOM",
    },
    {
        "incident_no": "INC-2024-0010",
        "title": "Cross-AZ network latency spike during AZ failover",
        "description": "Inter-AZ latency jumped from 2ms to 200ms between AZ-a and AZ-b. Synchronous replication delayed by 15s. Consensus (Raft) leader election flapping. Cluster in split-brain risk.",
        "root_cause": "AWS Direct Connect fiber cut in us-east-1 reduced inter-AZ bandwidth, causing congestion and bufferbloat. Traffic was routed through a saturated backup path. AWS Status Dashboard confirmed the incident 15min after detection.",
        "resolution": "1. Triggered manual AZ isolation to route all traffic within AZ-a only. 2. Promoted local replicas to primary to avoid cross-AZ consensus. 3. AWS resolved the fiber issue after 2h. 4. Added cross-AZ latency alert >10ms.",
        "action_plan": "1. Immediate: check cloud provider status. 2. Isolate to single AZ if possible. 3. Promote local replicas. 4. Add cross-AZ latency monitoring. 5. Review multi-AZ architecture for single-AZ degradation modes.",
        "severity": "P0",
        "service_name": "etcd-cluster",
        "category": "network",
        "status": "resolved",
        "error_type": "timeout",
    },
    # ═══ Category: Application ═══
    {
        "incident_no": "INC-2024-0011",
        "title": "Java OOM heap dump after rolling deployment",
        "description": "After deploying v2.4.1 to production, 3 out of 10 instances crashed with java.lang.OutOfMemoryError: Java heap space within 10min. Heap dump shows 4.2GB occupied by byte[] (90%). GC logs show full GC every 8s with no reclaim.",
        "root_cause": "v2.4.1 introduced a CSV export feature that loaded the entire result set into memory using ByteArrayOutputStream. A user triggered export of 5M rows (2GB CSV in memory * 2 threads = 4GB). No streaming or row-limit was implemented.",
        "resolution": "1. Rolled back to v2.4.0. 2. Rewrote CSV export to use StreamingResponseBody with chunked writes (no full in-memory load). 3. Added row limit of 100K for exports with cursor pagination. 4. Set -XX:+HeapDumpOnOutOfMemoryError -Xmx2g.",
        "action_plan": "1. Immediate: rollback deployment. 2. Capture heap dump for analysis. 3. Identify memory hotspot (often byte[] for serialization). 4. Switch to streaming/chunked I/O. 5. Add row limits. 6. Review JVM GC settings.",
        "severity": "P0",
        "service_name": "reporting-service",
        "category": "application",
        "status": "resolved",
        "error_type": "OOM",
    },
    {
        "incident_no": "INC-2024-0012",
        "title": "Node.js event loop blocked causing health check timeouts",
        "description": "Node.js app health-check endpoint timing out (3s threshold). Event loop lag metric shows 4200ms max. CPU at 30% — not CPU-bound. Heap 150MB/512MB — not GC thrashing. Requests queued but not processed.",
        "root_cause": "Synchronous crypto.randomBytes(256) called inside a hot-path request handler. It blocked the event loop while waiting for entropy. Under 500 concurrent connections, each blocking call queued up, cascading to full event-loop starvation.",
        "resolution": "1. Replaced crypto.randomBytes with crypto.randomBytes (async/callback version). 2. Added --trace-event-loop to identify other blocking calls. 3. Set up event-loop-lag alert at >200ms. 4. Moved heavy crypto to worker_threads pool.",
        "action_plan": "1. Identify blocking calls via --trace-event-loop or clinic.js. 2. Replace sync crypto, fs, zlib calls with async equivalents. 3. Offload CPU-heavy work to worker threads. 4. Add event-loop lag monitoring.",
        "severity": "P1",
        "service_name": "auth-service",
        "category": "application",
        "status": "resolved",
        "error_type": "timeout",
    },
    {
        "incident_no": "INC-2024-0013",
        "title": "Race condition in order status state machine",
        "description": "Orders stuck in 'processing' state after payment confirmation webhook. Payment provider confirmed success but order never transitioned to 'confirmed'. DB shows payment.status='paid' but order.status='processing'. Affects 3% of orders.",
        "root_cause": "Race condition: payment webhook and order timeout-cancel job both read order.status='processing', then each tried to UPDATE to 'confirmed' and 'cancelled' respectively. The job that arrived second won, overwriting the first transition with a lost update.",
        "resolution": "1. Added SELECT ... FOR UPDATE in order status transition to serialize access. 2. Changed to UPDATE orders SET status='confirmed' WHERE status='processing' (compare-and-swap). 3. Added idempotency key on webhook handler. 4. Built reconciliation job to fix stuck orders.",
        "action_plan": "1. Immediate: identify and manually fix stuck orders. 2. Add pessimistic locking on status transitions. 3. Use CAS UPDATE pattern (WHERE current_status = expected). 4. Add idempotency for webhooks. 5. Create reconciliation background job.",
        "severity": "P1",
        "service_name": "order-service",
        "category": "application",
        "status": "resolved",
        "error_type": "race_condition",
    },
    {
        "incident_no": "INC-2024-0014",
        "title": "Memory leak in Python service after 48h uptime",
        "description": "Python (FastAPI) service memory RSS grows from 200MB to 3.5GB over 48h, then gets OOMKilled. Memory profiling with tracemalloc shows top allocation: asyncio.Task objects (2.1M instances). No GC collection of completed tasks.",
        "root_cause": "asyncio.create_task() was called in a request handler without storing the task reference or awaiting it. Python's GC doesn't collect running tasks. Under load, 200 completed-but-unreferenced tasks leaked per second, accumulating 2M tasks over 48h.",
        "resolution": "1. Added TaskSet utility to track spawned tasks and clean up on completion. 2. Set asyncio.Task.add_done_callback to self-remove. 3. Added max-concurrent-tasks semaphore (limit 100). 4. Deploy with --max-requests 10000 + pre-emptive restart at 24h as safety net.",
        "action_plan": "1. Profile memory with tracemalloc. 2. Identify leaked object types (Task, connection, dict). 3. Ensure tasks are cleaned up on completion. 4. Add concurrency limits. 5. Consider pre-emptive restart as safety net.",
        "severity": "P2",
        "service_name": "notification-service",
        "category": "application",
        "status": "resolved",
        "error_type": "OOM",
    },
    {
        "incident_no": "INC-2024-0015",
        "title": "gRPC deadline exceeded on recommendation service",
        "description": "recommendation-service gRPC calls failing with DEADLINE_EXCEEDED. P99 latency 8s (SLO: 300ms). Upstream ML model serving responds in 150ms — delay is NOT in the model. Tracing shows time spent in gRPC layer waiting for connection.",
        "root_cause": "gRPC channel pool was configured with maxConnections=5 but the load balancer was distributing 500 req/s across 5 connections. TCP head-of-line blocking caused later requests on the same connection to wait for earlier slow responses. The slow responses were themselves caused by HOL blocking (vicious cycle).",
        "resolution": "1. Increased maxConnections from 5 to 200 (one per concurrent request). 2. Enabled HTTP/2 max concurrent streams = 1 to prevent HOL at gRPC level. 3. Set keepalive with timeout=10s and permit-keepalive-without-calls. 4. Changed to round_robin LB policy.",
        "action_plan": "1. Check gRPC channel pool size and LB policy. 2. Increase connections per instance. 3. Set max concurrent streams = 1. 4. Tune keepalive settings. 5. Check for HOL blocking via tracing spans.",
        "severity": "P1",
        "service_name": "recommendation-service",
        "category": "application",
        "status": "resolved",
        "error_type": "timeout",
    },
    # ═══ Category: Infrastructure ═══
    {
        "incident_no": "INC-2024-0016",
        "title": "Kubernetes node NotReady — disk pressure",
        "description": "Node ip-10-0-3-45 went NotReady. kubelet logs show 'DiskPressure: available 3%'. Pods on this node being evicted. Node has 100GB EBS, df shows /var/lib/docker 92% full. New pod scheduling failing across the cluster.",
        "root_cause": "Docker image garbage collection threshold was set to 90% but node-slow disk alert was set to 85% (below GC trigger). Old images accumulated during 4 deployments/day without cleanup. Over 2 weeks, unused images consumed 60GB.",
        "resolution": "1. Manually ran docker image prune -a -f to free 55GB. 2. Lowered image GC threshold to 70%. 3. Added kubelet flag --image-gc-high-threshold=70. 4. Added disk usage alert at 75% (above GC but before pressure).",
        "action_plan": "1. Immediate: prune unused Docker images. 2. Check kubelet image GC thresholds. 3. Set GC threshold below alert threshold. 4. Add disk pressure monitoring per node.",
        "severity": "P1",
        "service_name": "k8s-cluster",
        "category": "infrastructure",
        "status": "resolved",
        "error_type": "resource_exhaustion",
    },
    {
        "incident_no": "INC-2024-0017",
        "title": "AWS ECS service unable to place tasks — insufficient memory",
        "description": "ECS service deploy rolling update stuck for 30min. Events log: 'service xxx was unable to place a task because no container instance met all of its requirements'. Cluster all instances at 95%+ memory reservation.",
        "root_cause": "New deployment bumped task memory from 512MB to 1024MB (soft limit). ECS scheduler needs to place new task before draining old one (rolling update). With existing 512MB*8 tasks = 4GB reserved, no instance had 1GB free for the new task.",
        "resolution": "1. Temporarily scaled out cluster by 2 instances via ASG desired count. 2. Let deployment complete. 3. Scaled back in after old tasks drained. 4. Updated capacity planning to account for burst headroom during deployments (1.5x peak).",
        "action_plan": "1. Immediate: add cluster capacity (new instances). 2. Check ECS events for placement failures. 3. Calculate headroom needed for rolling update. 4. Adjust cluster autoscaling to maintain burst buffer. 5. Review per-task memory reservations.",
        "severity": "P1",
        "service_name": "ecs-cluster",
        "category": "infrastructure",
        "status": "resolved",
        "error_type": "resource_exhaustion",
    },
    {
        "incident_no": "INC-2024-0018",
        "title": "Prometheus disk full — time-series database corruption",
        "description": "Prometheus pod crash looping with 'opening storage failed: /prometheus/01H...: invalid magic number 0'. Disk 100% full. TSDB WAL checkpoint corrupted. Monitoring blackout — no metrics for last 20min across entire org.",
        "root_cause": "Cardinality explosion: a new deployment added a label 'request_id' (UUID) to all HTTP metrics. Each unique UUID created a new time series. From 50K to 15M active series in 2h. TSDB WAL grew from 2GB to 50GB, filling the 80GB PVC.",
        "resolution": "1. Restored from last TSDB snapshot (30min data loss). 2. Rolled back deployment that added request_id label. 3. Added relabel_config to drop request_id at scrape time. 4. Set --storage.tsdb.retention.size=60GB. 5. Added cardinality alert at 500K series.",
        "action_plan": "1. Immediate: check disk space, restore from snapshot if corrupted. 2. Identify cardinality spike source (label values). 3. Drop high-cardinality labels. 4. Set retention size limit. 5. Add cardinality + disk alerts.",
        "severity": "P0",
        "service_name": "monitoring",
        "category": "infrastructure",
        "status": "resolved",
        "error_type": "resource_exhaustion",
    },
    {
        "incident_no": "INC-2024-0019",
        "title": "CI/CD pipeline hung on git clone — GitHub rate limit",
        "description": "All CI/CD pipelines stuck at 'git clone' step. Error: 'remote: Repository not found. fatal: Authentication failed...' — but credentials are correct. Started at 14:00 UTC across all pipelines simultaneously.",
        "root_cause": "Organization hit GitHub's secondary rate limit (100 concurrent git operations per org). A scheduled job triggered 200 parallel builds, each doing git clone simultaneously. GitHub returned 429s which the runner interpreted as auth failure.",
        "resolution": "1. Cancelled 150 queued builds to drop below rate limit. 2. Configured git clone --depth=1 to reduce data transfer. 3. Added git cache proxy (git-cache) to serve clones from within VPC. 4. Implemented staggered scheduling (max 50 concurrent clones).",
        "action_plan": "1. Immediate: cancel excessive builds. 2. Check GitHub rate-limit headers. 3. Set up git cache/mirror internally. 4. Implement clone staggering. 5. Use shallow clones where possible.",
        "severity": "P1",
        "service_name": "cicd-pipeline",
        "category": "infrastructure",
        "status": "resolved",
        "error_type": "rate_limit",
    },
    {
        "incident_no": "INC-2024-0020",
        "title": "Terraform state lock timeout blocking all deployments",
        "description": "All terraform apply commands failing with 'Error acquiring the state lock: ConditionalCheckFailedException'. Lock held for 45min. DynamoDB lock table shows lock acquired by a CI run that was terminated by timeout. No heartbeat to release.",
        "root_cause": "CI job (terraform plan) acquired state lock, then exceeded its 30min timeout. The runner was killed but never ran terraform force-unlock. DynamoDB item persisted without TTL. Manual intervention required to delete lock.",
        "resolution": "1. Manually deleted lock item from DynamoDB via AWS Console. 2. Added TTL attribute to lock items (auto-expire after 15min). 3. Reduced terraform plan timeout to 20min. 4. Added pre-kill signal handler (SIGTERM → terraform force-unlock).",
        "action_plan": "1. Immediate: force-unlock or delete lock from DynamoDB. 2. Check who acquired lock and why it stalled. 3. Add TTL to lock table items. 4. Implement graceful unlock on SIGTERM. 5. Set CI timeouts below lock TTL.",
        "severity": "P1",
        "service_name": "infra-tf",
        "category": "infrastructure",
        "status": "resolved",
        "error_type": "deadlock",
    },
    # ═══ Category: Application — additional ═══
    {
        "incident_no": "INC-2024-0021",
        "title": "Kafka consumer lag 50K — notification delay 20min",
        "description": "Kafka consumer group 'notif-push' lag reached 50K messages. P99 notification delivery delay 20min (SLO: 30s). Consumer CPU at 15% — not CPU-bound. No rebalancing in consumer group logs. All partitions assigned. Broker disk IO normal.",
        "root_cause": "Consumer was using synchronous HTTP call to Firebase Cloud Messaging (FCM) inside each message handler. FCM API had intermittent 2s latency on 30% of calls. With 10 consumer threads, effective throughput dropped from 1000 msg/s to 50 msg/s. Messages queued up in Kafka creating the lag.",
        "resolution": "1. Moved FCM push to async via asyncio.ensure_future. 2. Increased consumer threads from 10 to 50. 3. Added circuit breaker with 500ms timeout to FCM calls. 4. Set max.poll.records=100 to reduce per-batch processing time.",
        "action_plan": "1. Check consumer lag: kafka-consumer-groups --describe. 2. Profile handler latency to find bottleneck. 3. Move blocking I/O to async pool. 4. Scale consumer instances horizontally. 5. Add consumer lag alerts >1000.",
        "severity": "P1",
        "service_name": "notification-service",
        "category": "application",
        "status": "resolved",
        "error_type": "timeout",
    },
    {
        "incident_no": "INC-2024-0022",
        "title": "Zero-downtime deploy stuck — health check never passes",
        "description": "Blue-green deployment stuck for 45min. New (green) pods in CrashLoopBackOff: 'readiness probe failed: Get http://10.0.1.45:8080/health: dial tcp 10.0.1.45:8080: connect: connection refused'. Application logs show 'FATAL: password authentication failed for user app_user'. ConfigMap has correct password.",
        "root_cause": "Deployment updated DB password via Kubernetes Secret, but the green pods were using a cached version from /etc/secrets mounted at pod start. The Secret was updated correctly, but pods spawned before the Secret update didn't pick up the new value (Kubernetes does not auto-reload mounted Secrets). Manual rolling restart resolved it.",
        "resolution": "1. Deleted all green pods to force recreation with fresh Secret mount. 2. Added Reloader tool to auto-restart pods on Secret changes. 3. Changed health check from /health (simple port check) to /healthz (validates DB connection). 4. Added deploy hook to verify Secret propagation before green pod creation.",
        "action_plan": "1. Check pod logs for startup errors (kubectl logs -l version=green). 2. Verify Secret is propagated: kubectl get secret -o yaml | grep <key>. 3. Force restart pods if Secret changed. 4. Add Reloader or stakater/Reloader. 5. Change health check endpoint to validate dependencies.",
        "severity": "P1",
        "service_name": "order-service",
        "category": "application",
        "status": "resolved",
        "error_type": "config_error",
    },
    # ═══ Category: Network — additional ═══
    {
        "incident_no": "INC-2024-0023",
        "title": "VPC peering connection dropped — multi-region replication broken",
        "description": "Cross-region VPC peering between us-east-1 and eu-west-1 dropped at 03:00 UTC. MySQL cross-region replication stopped. Replica lag grew to 4GB. DR site out of sync. CloudWatch VPCFlow logs show 'Action: REJECT' for all cross-VPC traffic starting at 02:58 UTC.",
        "root_cause": "Infrastructure-as-code pipeline applied a Terraform change that rebuilt the VPC peering connection with a different CIDR range. The old peering connection was deleted before the new one was fully established (missing create_before_destroy lifecycle rule). A 6-minute window of no connectivity occurred during re-creation.",
        "resolution": "1. Manually accepted the new pending peering connection in AWS Console. 2. Updated route tables in both VPCs to use the new peering connection ID (pcx-xxxxx). 3. Added lifecycle { create_before_destroy = true } to aws_vpc_peering_connection in Terraform. 4. Added AWS Config rule to alert on VPC peering deletion.",
        "action_plan": "1. Verify peering status: aws ec2 describe-vpc-peering-connections. 2. Check route tables in both VPCs. 3. If pending, accept peering manually. 4. Update Terraform with create_before_destroy. 5. Enable VPC Flow Logs alerting on REJECT actions.",
        "severity": "P0",
        "service_name": "infra-network",
        "category": "network",
        "status": "resolved",
        "error_type": "config_error",
    },
    {
        "incident_no": "INC-2024-0024",
        "title": "WebSocket connections dropping every 60s — mobile app reconnect storm",
        "description": "iOS and Android apps experiencing WebSocket disconnects exactly every 60 seconds. Reconnection creates 5000 new connections/second, overloading the WS gateway. Nginx access.log shows 499 status (client closed request) on /ws endpoint. ALB idle timeout set to 60s. WebSocket ping interval set to 120s.",
        "root_cause": "AWS ALB idle timeout was set to 60 seconds (default). Application WebSocket ping/pong interval was 120 seconds. Since no data frames were sent within the 60s idle window when users were just reading content, ALB silently closed the TCP connection. The client-side reconnection logic triggered exactly at the ALB timeout boundary, creating a 1-minute reconnect storm cycle.",
        "resolution": "1. Increased ALB idle timeout to 300s (matching WebSocket max idle). 2. Reduced application WebSocket ping interval to 25s (below 60s ALB threshold). 3. Added exponential backoff jitter to client reconnection (1s, 2s, 4s, 8s, 16s, max 30s). 4. Added WebSocket connection count dashboard with 1min reconnect-rate metric.",
        "action_plan": "1. Check LB idle timeout vs application keepalive/ping interval. 2. Ensure ping interval < LB idle timeout. 3. Add jittered exponential backoff to client reconnects. 4. Monitor reconnect rate as early warning signal.",
        "severity": "P1",
        "service_name": "websocket-gateway",
        "category": "network",
        "status": "resolved",
        "error_type": "timeout",
    },
    # ═══ Category: Security ═══
    {
        "incident_no": "INC-2024-0025",
        "title": "Suspicious spike in failed login attempts — potential brute force",
        "description": "Auth service logging 50K failed login attempts/minute from 340 unique IPs across 12 countries. 99% targeting /api/auth/login with common passwords. Rate limiter configured at 5 req/min per IP — not triggering because attacks are distributed. 3 accounts successfully compromised (confirmed unauthorized orders placed).",
        "root_cause": "Rate limiter was IP-based, but attackers used a distributed botnet with 340 unique IPs. They stayed well below the 5 req/min threshold per IP. No account-level rate limiting was in place. The compromised accounts had no 2FA enabled — they were legacy accounts grandfathered before the 2FA mandate.",
        "resolution": "1. Force-reset passwords for 3 compromised accounts and notified users. 2. Implemented account-level rate limiting (10 failed attempts per account per 5min). 3. Blocked IPs via AWS WAF rate-based rule at 100 req/5min per IP. 4. Forced 2FA enrollment for all accounts without it. 5. Added anomaly detection: login_attempts_from_new_country trigger.",
        "action_plan": "1. Immediate: block attacking IPs in WAF/security group. 2. Force-reset compromised accounts. 3. Implement account-level rate limiting. 4. Audit 2FA coverage — enforce for all accounts. 5. Set up geo-anomaly alerts for login patterns.",
        "severity": "P0",
        "service_name": "auth-service",
        "category": "security",
        "status": "resolved",
        "error_type": "auth_error",
    },
    {
        "incident_no": "INC-2024-0026",
        "title": "S3 bucket public-read ACL applied by misconfigured CI pipeline",
        "description": "Security scanner flagged s3://app-user-uploads with public-read ACL at 16:30 UTC. Bucket contains 2.3M user-uploaded documents including KYC/ID scans (PII). CloudTrail shows PutBucketAcl API call from IAM role 'ci-deployer' at 16:28 UTC. Access logs show 12 anonymous GET requests in the 2-minute exposure window.",
        "root_cause": "A CI pipeline for a static website deployment used a misconfigured Terraform module (terraform-aws-s3-bucket v3.1 with default acl='public-read'). The module was intended for the public assets bucket but was accidentally pointed at the user-uploads bucket via a copy-paste error in the CI variable definition.",
        "resolution": "1. Immediately reverted ACL to private via AWS Console (within 3min of alert). 2. Quarantined the CI pipeline that applied the change. 3. Audited CloudTrail to confirm exactly 12 objects were accessed (none were KYC documents — all were public product images). 4. Added SCP to deny s3:PutBucketAcl with public-read/private. 5. Added AWS Config rule 's3-bucket-public-read-prohibited' with auto-remediation.",
        "action_plan": "1. Immediate: revert ACL to private. 2. Audit CloudTrail for unauthorized access during exposure window. 3. Notify compliance/legal if PII was accessed. 4. Add SCP to block public ACLs org-wide. 5. Add AWS Config auto-remediation rules.",
        "severity": "P0",
        "service_name": "storage-s3",
        "category": "security",
        "status": "resolved",
        "error_type": "config_error",
    },
    # ═══ Category: Application — with different statuses ═══
    {
        "incident_no": "INC-2025-0002",
        "title": "Search latency degrading — investigating Elasticsearch query regression",
        "description": "Search service P95 latency increased from 80ms to 450ms over the last 4 hours. No deployment in that window. No traffic spike observed. Elasticsearch cluster healthy (green, no shard movement). Hot threads show significant time spent in ScriptService for custom scoring script. Index size grew 15% in 4h (normal rate is 2%/day).",
        "severity": "P2",
        "service_name": "search-service",
        "category": "application",
        "status": "investigating",
        "error_type": "timeout",
    },
    {
        "incident_no": "INC-2025-0003",
        "title": "Third-party payment gateway 503 — failover activated",
        "description": "Primary payment gateway (Stripe) returning HTTP 503 on /v1/charges since 11:15 UTC. Failover to secondary gateway (Adyen) activated automatically. Adyen processing 100% of transactions at 3x normal volume. Adyen P99 latency at 800ms (normal: 200ms). Circuit breaker on Stripe still open — retry timer counting down.",
        "root_cause": "Stripe incident confirmed via status.stripe.com — 'Elevated API Errors in us-east-1'. Our circuit breaker (resilience4j) detected 50% failure rate and opened after 100 requests. Failover logic in PaymentRouter correctly redirected to Adyen. Known issue: Adyen not capacity-tested for 100% failover volume.",
        "resolution": "1. Confirmed Stripe incident — our systems operating as designed. 2. Scaled Adyen integration pods from 10 to 30 to handle volume. 3. Added connection pool warming on Adyen side. 4. Monitoring Stripe status page for resolution — will close circuit breaker manually once confirmed.",
        "action_plan": "1. Verify upstream provider status page. 2. Confirm failover is routing correctly. 3. Scale secondary provider if needed. 4. Monitor primary for recovery. 5. Post-incident: capacity-test failover at 100% load.",
        "severity": "P1",
        "service_name": "payment-service",
        "category": "application",
        "status": "mitigated",
        "error_type": "dependency_failure",
    },
    # ═══ Category: Database — additional ═══
    {
        "incident_no": "INC-2024-0027",
        "title": "MongoDB replica set election storm — primary flapping 4x/hour",
        "description": "MongoDB replica set 'rs-orders' experiencing primary re-elections every 15 minutes for the last 3 hours. Each election causes 3-8s write unavailability. Application seeing intermittent MongoTimeoutException on writes. replSetGetStatus shows priority and votes are correctly configured for all 3 members. oplog size adequate at 50GB.",
        "root_cause": "Secondary node in a different AZ had intermittent network packet loss (0.5%) due to a faulty fiber transceiver. The secondary would briefly lose heartbeat (electionTimeoutMillis=10000), triggering an election. It would rejoin, sync, then lose heartbeat again — creating a 15-minute election cycle. The faulty transceiver was not detected by AWS health checks because ping succeeded for 99.5% of packets.",
        "resolution": "1. Forced the faulty secondary to step down (rs.stepDown()) and removed it from the replica set temporarily. 2. AWS replaced the faulty transceiver after we filed a ticket with traceroute evidence. 3. Re-added the node after transceiver replacement. 4. Increased electionTimeoutMillis to 20000 to reduce sensitivity to transient network issues. 5. Added cross-AZ latency and packet-loss monitoring.",
        "action_plan": "1. Check replica set status: rs.status(). 2. Examine node logs for heartbeat timeouts. 3. Isolate faulty node temporarily. 4. Check network health between AZs (packet loss, latency jitter). 5. File ticket with cloud provider if hardware issue.",
        "severity": "P1",
        "service_name": "order-service",
        "category": "database",
        "status": "resolved",
        "error_type": "timeout",
    },
    {
        "incident_no": "INC-2024-0028",
        "title": "Cassandra nodetool repair backlog causing read-repair timeout",
        "description": "Cassandra cluster read latency P99 increased from 15ms to 2.4s. nodetool tpstats shows ReadStage pending=8500. Read repair chance=0.1 but triggered on 80% of reads due to inconsistent replicas. nodetool repair has not been run in 14 days (SLO: 7 days). HintedHandoff queue at 2M pending hints.",
        "root_cause": "Scheduled repair cron job was silently failing for 14 days due to an expired SSL certificate on the JMX connection. nodetool repair could not authenticate. Without regular repairs, replicas diverged, causing read-repair on most reads. Each read-repair is a full read of all replicas + comparison, dramatically increasing read latency.",
        "resolution": "1. Updated JMX SSL certificate and restarted repair cron job. 2. Ran full sequential repair: nodetool repair -full -seq -j 4 on all nodes (took 8h). 3. Reduced read_repair_chance from 0.1 to 0.01 (production guidance). 4. Added monitoring alert: last_repair_time > 7 days. 5. Added a canary repair job that validates JMX connectivity daily.",
        "action_plan": "1. Check last repair time: nodetool repair -pr --dry-run. 2. Run nodetool tpstats to find bottleneck stage. 3. Verify JMX connectivity for repair tool. 4. Run full repair during maintenance window. 5. Add repair monitoring and canary check.",
        "severity": "P1",
        "service_name": "order-service",
        "category": "database",
        "status": "resolved",
        "error_type": "timeout",
    },
    # ═══ Category: Infrastructure — additional ═══
    {
        "incident_no": "INC-2025-0004",
        "title": "Node group scaling stuck — ASG unable to launch new instances",
        "description": "EKS node group 'compute-heavy' failed to scale from 10 to 15 nodes. Pending pods in Unschedulable state. ASG activity history shows 'Launching a new EC2 instance: i-xxxxx. Status Reason: The requested configuration is currently not supported. Launching EC2 instance failed.' CapacityReservation shows no matching reservations.",
        "severity": "P2",
        "service_name": "k8s-cluster",
        "category": "infrastructure",
        "status": "open",
        "error_type": "resource_exhaustion",
    },
    {
        "incident_no": "INC-2024-0029",
        "title": "Artifact repository disk full — npm publish failing",
        "description": "Internal Nexus artifact repository disk usage hit 98%. npm publish commands failing with '413 Request Entity Too Large'. Docker push returning 500 Internal Server Error on /v2/blobs/uploads/. Maven deploy also affected. CI pipelines blocked for all teams. Repository has 500GB EBS volume.",
        "root_cause": "Docker image cleanup policy was set to keep last 10 versions per image. A microservices migration created 200 new Docker repos in 2 weeks (50 microservices × 4 environments). Each image averaging 300MB × 10 versions = 600GB total Docker storage. Combined with 400GB of npm artifacts, total usage exceeded the 500GB volume.",
        "resolution": "1. Manually deleted old Docker images older than 7 days (keep < 5 versions). 2. Updated cleanup policy: keep last 5 Docker images, 3 npm versions. 3. Increased EBS volume to 1TB and expanded filesystem. 4. Divided Nexus into separate blob stores: Docker (750GB) and npm/Maven (250GB). 5. Added disk usage alert at 70% and 85%.",
        "action_plan": "1. Immediate: delete old artifacts to free space. 2. Check cleanup policy settings. 3. Identify largest storage consumers (Docker images usually). 4. Resize volume if needed. 5. Split blob stores by artifact type. 6. Add disk usage monitoring.",
        "severity": "P1",
        "service_name": "artifact-repo",
        "category": "infrastructure",
        "status": "resolved",
        "error_type": "resource_exhaustion",
    },
    # ═══ Category: Application — more variations ═══
    {
        "incident_no": "INC-2024-0030",
        "title": "Memory leak in image processing worker after watermark feature rollout",
        "description": "Image processing workers OOMKilled after 2-3h of uptime following watermark feature deployment. RSS grows linearly at 50MB/min from 200MB to 2GB before OOM. Heap dump analysis shows 1.4M instances of java.awt.image.BufferedImage held in a static ConcurrentHashMap cache. Cache size was supposed to be LRU with max 100 entries but the eviction listener was never registered.",
        "root_cause": "The ImageCache class used a LinkedHashMap with accessOrder=true and a removeEldestEntry override for LRU eviction. However, the Map was wrapped in Collections.synchronizedMap() which doesn't delegate to the LinkedHashMap's removeEldestEntry. The method was never called. The cache grew unbounded, holding every image ever processed by that worker process.",
        "resolution": "1. Replaced Collections.synchronizedMap with Guava Cache (CacheBuilder.maximumSize(100).expireAfterAccess(5, MINUTES)). 2. Added direct memory buffer pool for image processing (MaxDirectMemorySize=512m). 3. Deployed with -XX:+ExitOnOutOfMemoryError to force pod restart on OOM. 4. Set pod memory limit=3Gi with requests=2Gi.",
        "action_plan": "1. Capture heap dump before OOM for analysis. 2. Identify object accumulation pattern (usually in caches or static collections). 3. Check cache eviction logic — ensure LRU/TTL actually works. 4. Consider Guava Cache or Caffeine for robust caching. 5. Set memory limits with graceful degradation.",
        "severity": "P1",
        "service_name": "image-service",
        "category": "application",
        "status": "resolved",
        "error_type": "OOM",
    },
    {
        "incident_no": "INC-2025-0005",
        "title": "API rate limiter misconfiguration — legitimate traffic blocked",
        "description": "Customer reports: mobile app returning '429 Too Many Requests' during normal usage. Rate limiter config was updated 2h ago via feature flag. Current config: X-RateLimit-Limit=10, X-RateLimit-Window=1s. Previously was 100/min. Users seeing error after 2-3 screen transitions. Customer support tickets +200 in last hour.",
        "root_cause": "SRE updated rate limiter via feature flag to mitigate a suspected DDoS. Intended value was 10 requests per second but the configuration UI used a dropdown with 'per second' / 'per minute' options. The value '10 per minute' was selected but the dropdown was misread as 'per second'. The effective limit became 10 requests per minute (previously 100/min) — blocking 90% of legitimate traffic.",
        "severity": "P0",
        "service_name": "api-gateway",
        "category": "application",
        "status": "investigating",
        "error_type": "config_error",
    },
    # ═══ Multi-version ticket — active with history ═══
    {
        "incident_no": "INC-2025-0006",
        "title": "Critical: user data export job leaking PII to logs",
        "description": "Data export job for GDPR compliance started logging full user records (including email, phone, address) to stdout at INFO level. Logs shipped to centralized ELK stack accessible to all engineering. Discovered by security team during routine log audit. Affected records: approximately 47K users over 72 hours of job execution. Export job currently stopped.",
        "root_cause": "DataExportService used Lombok @ToString annotation on the UserRecord model class, which auto-generates a toString() including all fields. The service logged 'Processing record: {}' + record at INFO level. When a developer changed log level from DEBUG to INFO for debugging a separate issue 3 days ago, it was never reverted. The @ToString annotation should have been annotated with @ToString.Exclude on PII fields.",
        "resolution": "1. Immediately stopped the export job and rotated all affected log files. 2. Added @ToString.Exclude annotations on all PII fields in UserRecord (email, phone, address, ssnLast4). 3. Implemented log redaction filter at logback level — pattern-match PII and replace with [REDACTED]. 4. Restricted ELK access to PII-containing indices to security-team only. 5. Conducted mandatory code review for all @ToString-annotated model classes. 6. Added Checkstyle rule to forbid @ToString without explicit @ToString.Exclude on PII fields.",
        "action_plan": "1. Immediate: stop affected job. 2. Identify all log files containing PII — rotate and secure. 3. Audit code for @ToString usage on model classes. 4. Add log-level redaction filter. 5. Restrict log access to PII indices. 6. Add automated PII leak detection in CI pipeline.",
        "severity": "P0",
        "service_name": "data-export-service",
        "category": "security",
        "status": "resolved",
        "error_type": "config_error",
    },
]


def seed():
    Base.metadata.create_all(engine)
    print("Tables created (if not existed).")

    ids = ingest_tickets_batch(SEED_TICKETS)
    print(f"Seeded {len(ids)} tickets:")
    for i, tid in enumerate(ids):
        print(f"  [{i+1}] {tid}")
    print("Done.")


if __name__ == "__main__":
    seed()
